package com.workin.legacy.dashboard;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;

import com.workin.legacy.LegacyClock;
import com.workin.legacy.payroll.LegacyPenaltyAmounts;

/**
 * {@code dashboard/stats.php} -- twenty response keys assembled from fourteen
 * queries plus the turnover and penalty-amount helpers.
 *
 * <h2>Two shapes of "empty" in one payload, and the difference is observable</h2>
 * <p>PHP writes {@code empty($x) ? (object)[] : $x} for the map-valued keys, so
 * an empty map serialises as <b>{@code {} }</b> rather than {@code []} -- the
 * cast exists precisely because an empty PHP array would otherwise encode as a
 * JSON array and change the value's type for the client. The two <em>list</em>
 * keys, {@code workforce_planning_stats} and {@code new_employees_by_month},
 * carry no such cast and correctly stay {@code []} when empty. A Java
 * {@code Map} and {@code List} reproduce both without the cast, but the
 * distinction is stated because it is easy to "tidy" one into the other.
 *
 * <h2>The month series is always twelve entries; the day series is sparse</h2>
 * <p>{@code new_employees_by_month} is generated by walking a cursor twelve
 * times and defaulting missing months to zero, so a client always receives
 * twelve points. {@code daily_attendance_stats} is whatever the {@code GROUP BY}
 * returned -- days with no attendance are simply absent. Two adjacent
 * time-series keys with opposite density conventions.
 */
@Service
public class LegacyDashboardService {

	private final LegacyDashboardStore store;
	private final LegacyTurnover turnover;
	private final LegacyPenaltyAmounts penaltyAmounts;
	private final LegacyClock clock;

	public LegacyDashboardService(
			LegacyDashboardStore store, LegacyTurnover turnover,
			LegacyPenaltyAmounts penaltyAmounts, LegacyClock clock) {
		this.store = store;
		this.turnover = turnover;
		this.penaltyAmounts = penaltyAmounts;
		this.clock = clock;
	}

	public Map<String, Object> stats(long companyId) {
		LocalDate today = clock.today();

		LegacyDashboardStore.SalaryTotals salaries = store.salaryTotals(companyId);

		String monthStart = today.withDayOfMonth(1).toString();
		String yearStart = today.withDayOfYear(1).toString();
		String todayText = today.toString();

		Map<String, Object> out = new LinkedHashMap<>();
		out.put("total_employees", store.totalEmployees(companyId));
		out.put("total_branches", store.totalBranches(companyId));
		out.put("total_gross_salaries", salaries.gross());
		out.put("total_basic_salaries", salaries.basic());
		out.put("salaries_by_department", store.salariesByDepartment(companyId));
		out.put("employees_by_branch", store.employeesByBranch(companyId));
		out.put("employees_by_department", store.employeesByDepartment(companyId));
		out.put("workforce_planning_stats", store.workforcePlanning(companyId));
		out.put("daily_attendance_stats", store.dailyAttendance(companyId));
		out.put("attendance_by_department_stats", attendanceShares(companyId));
		out.put("resignations_count", store.resignations(companyId, today.getYear()));
		out.put("monthly_turnover_rate", turnover.rateForPeriod(companyId, monthStart, todayText));
		out.put("new_employee_turnover_rate", turnover.newEmployeeNinetyDayRate(companyId, today));
		out.put("annual_turnover_rate", turnover.rateForPeriod(companyId, yearStart, todayText));
		out.put("total_penalties", store.totalPenalties(companyId));
		out.put("total_penalties_amount",
				penaltyAmounts.totalAmount(List.of("e.company_id=?"), List.of(companyId)));
		out.put("penalties_by_department", store.penaltiesByDepartment(companyId));
		out.put("employees_by_gender", store.employeesByGender(companyId));
		out.put("employees_by_age_bracket", store.employeesByAgeBracket(companyId));
		out.put("new_employees_by_month", newEmployeesByMonth(companyId, today));
		return out;
	}

	/**
	 * Attendance percentage per department, {@code round($count / $total * 100, 2)}.
	 *
	 * <p>A department with no active employees is present with a zero rather
	 * than absent or null. {@code round()} is applied to the result of the
	 * ternary, so <b>both</b> branches go through it -- the zero is not a
	 * special case that skips the rounding.
	 */
	private Map<String, Object> attendanceShares(long companyId) {
		Map<String, Object> out = new LinkedHashMap<>();
		for (LegacyDashboardStore.AttendanceShare share : store.attendanceByDepartment(companyId)) {
			double percentage = share.total() > 0
					? (double) share.present() / share.total() * 100
					: 0;
			out.put(share.departmentName(),
					BigDecimal.valueOf(percentage).setScale(2, RoundingMode.HALF_UP).doubleValue());
		}
		return out;
	}

	/**
	 * Twelve entries ending with the current month.
	 *
	 * <p>PHP walks {@code new DateTimeImmutable('first day of this month')}
	 * back eleven months and forward twelve times, so the window is always
	 * whole calendar months and always the same length regardless of what the
	 * query returned. Anchoring on the first of the month is what makes the
	 * {@code +1 month} steps safe -- stepping from a 31st would skip February.
	 */
	private List<Map<String, Object>> newEmployeesByMonth(long companyId, LocalDate today) {
		Map<String, Long> counts = store.newHiresByMonth(companyId);
		List<Map<String, Object>> out = new ArrayList<>();
		LocalDate cursor = today.withDayOfMonth(1).minusMonths(11);
		for (int i = 0; i < 12; i++) {
			String ym = "%04d-%02d".formatted(cursor.getYear(), cursor.getMonthValue());
			Map<String, Object> entry = new LinkedHashMap<>();
			entry.put("month", ym);
			entry.put("count", counts.getOrDefault(ym, 0L));
			out.add(entry);
			cursor = cursor.plusMonths(1);
		}
		return out;
	}
}
