name: Feature
description: Deliverable capability within an epic
title: "FEATURE "
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: Desired outcome
    validations:
      required: true
