name: Task
description: Concrete unit of work
title: "TASK "
labels: ["task"]
body:
  - type: textarea
    id: objective
    attributes:
      label: Objective
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: Definition of done
    validations:
      required: true
