#!/usr/bin/env bash
# Bring one profile's stack up and run the end-to-end suite against it.
#
#   ./run.sh local                 # API + deployment shape
#   ./run.sh integration           # ...plus the admin dashboard, over TLS
#   ./run.sh prod                  # the production shape, on a throwaway stack
#
# The admin dashboard only runs under `integration`: it needs TLS in front,
# because its session cookie is `secure` unconditionally, and that is the
# profile whose whole purpose is being pointed at by other people.
#
# Nothing here relaxes a control to make a test pass. The TLS is real TLS with a
# throwaway certificate; each profile runs exactly as it ships.
#
# `integration` and `prod` take their configuration from `.env.<profile>-e2e`,
# which this script generates and which is git-ignored. It deliberately does NOT
# read or write `.env.integration` / `.env.prod`: those are an operator's real
# files, and a test run must not be able to start a real deployment or leave
# throwaway secrets where a real one will pick them up.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY="$(dirname "$HERE")"
PROFILE="${1:-local}"
shift || true

case "$PROFILE" in
  local|integration|prod) ;;
  *) echo "usage: $0 <local|integration|prod> [playwright args]" >&2; exit 2 ;;
esac

say() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }

ADMIN_PASSWORD='e2e-verify-Pass123!'

compose() { (cd "$DEPLOY" && docker compose "$@"); }

# ---------------------------------------------------------------- environment
# Every value here is throwaway and fixed, so a run is reproducible. They are
# secrets only in the sense that the application requires them to be set; the
# stack they configure holds the sanitised seed and is destroyed afterwards.
write_env() {
  local path="$DEPLOY/.env.$PROFILE-e2e"
  [ -f "$path" ] && [ -z "${E2E_REGENERATE_ENV:-}" ] && return
  cat > "$path" <<ENV
# GENERATED by deploy/e2e/run.sh. Throwaway values for a throwaway stack.
# Not an operator's file: .env.integration and .env.prod are, and this is
# deliberately not either of them.
DB_NAME=workin
DB_USER=workin
DB_PASSWORD=e2e-throwaway-db-password
DB_ROOT_PASSWORD=e2e-throwaway-root-password
JWT_SECRET=e2e-throwaway-signing-secret-not-production-not-integration
ADMIN_PASSWORD=$ADMIN_PASSWORD
ADMIN_ACTIONS_ENABLED=${ADMIN_ACTIONS_ENABLED:-false}
# Only meaningful under integration, and only because a proxy is in front.
FORWARD_HEADERS_STRATEGY=native
APP_PUBLISHED_PORT=${APP_PUBLISHED_PORT:-8080}
DB_PUBLISHED_PORT=${DB_PUBLISHED_PORT:-13306}
E2E_HTTPS_PORT=${E2E_HTTPS_PORT:-8443}
ENV
  # Only production requires WhatsApp credentials, and only production's compose
  # refuses to start without them. Writing them for every profile made the
  # integration stack log "WhatsApp OTP delivery is configured" against a seed
  # derived from real customer data -- exactly what leaving them unset prevents.
  # The deployment-shape suite asserts they are absent outside prod.
  if [ "$PROFILE" = prod ]; then
    cat >> "$path" <<'ENVPROD'
WHATSAPP_API_TOKEN=e2e-throwaway-not-a-real-token
WHATSAPP_INSTANCE_ID=e2e-throwaway-not-a-real-instance
ENVPROD
  fi
  chmod 600 "$path"
}

DB_USER=workin
DB_PASSWORD=workin-local

case "$PROFILE" in
  local)
    FILES=(-f compose.local.yaml)
    ENVFILE=()
    PROJECTS=(--project=api --project=surface --project=deployment)
    ;;
  integration)
    write_env
    FILES=(-f compose.integration.yaml -f e2e/compose.proxy.yaml)
    ENVFILE=(--env-file ".env.$PROFILE-e2e")
    DB_PASSWORD=e2e-throwaway-db-password
    PROJECTS=(--project=api --project=surface --project=deployment --project=admin)
    # The integration profile enables administrative actions by default: there
    # is no legacy PHP admin surface beside this one for ADR-0015 prerequisite 7
    # to be about. So the administrative-action case runs here rather than
    # being skipped.
    : "${ADMIN_ACTIONS_ENABLED:=true}"
    ;;
  prod)
    write_env
    FILES=(-f compose.prod.yaml)
    ENVFILE=(--env-file ".env.$PROFILE-e2e")
    DB_PASSWORD=e2e-throwaway-db-password
    # Only the deployment shape. compose.prod.yaml mounts NO seed -- production
    # data arrives by a supervised restore, never by a file compose mounts -- so
    # the database is empty and there is nothing for the API journeys to read.
    # Restoring the dev seed into it is what seed_prod below does, when asked.
    PROJECTS=(--project=deployment)
    ;;
esac

APP_CONTAINER="workin-$PROFILE-app-1"
DB_CONTAINER="workin-$PROFILE-db-1"

# Outside the repository on purpose. validate_phase0's secret scan walks the
# working tree, not the index, so a git-ignored key still trips it -- and that
# is the scan behaving correctly, because its job is to catch a key before it
# is committed.
E2E_TLS_DIR="${E2E_TLS_DIR:-${TMPDIR:-/tmp}/workin-e2e-tls-$(id -u)}"
export E2E_TLS_DIR

if [ "$PROFILE" = integration ]; then
  say "TLS for the proxy ($E2E_TLS_DIR)"
  mkdir -p "$E2E_TLS_DIR"
  chmod 700 "$E2E_TLS_DIR"
  if [ ! -f "$E2E_TLS_DIR/server.crt" ] || [ -n "${E2E_REGENERATE_TLS:-}" ]; then
    openssl req -x509 -newkey rsa:2048 -nodes -days 30 \
      -keyout "$E2E_TLS_DIR/server.key" -out "$E2E_TLS_DIR/server.crt" \
      -subj "/CN=localhost" \
      -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" 2>/dev/null
    chmod 644 "$E2E_TLS_DIR/server.crt" "$E2E_TLS_DIR/server.key"
  fi
fi

say "node dependencies"
[ -d "$HERE/node_modules" ] || (cd "$HERE" && npm install --no-audit --no-fund)

say "starting the $PROFILE stack"
compose "${FILES[@]}" "${ENVFILE[@]}" up -d --build

if [ "$PROFILE" = prod ] && [ -n "${E2E_SEED_PROD:-}" ]; then
  # Production's compose mounts no seed on purpose. Restoring one by hand is
  # exactly the supervised step the real deployment takes, so doing it here is
  # the honest way to exercise the profile without inventing a shortcut in the
  # compose file that production would then also have.
  say "restoring the sanitised seed by hand (the supervised step, not a mount)"
  until docker exec "$DB_CONTAINER" mariadb -u"$DB_USER" -p"$DB_PASSWORD" \
      -e 'SELECT 1' workin >/dev/null 2>&1; do sleep 3; done
  docker exec -i "$DB_CONTAINER" mariadb -u"$DB_USER" -p"$DB_PASSWORD" workin \
    < "$DEPLOY/seed/dev-seed.sql" 2>&1 | grep -v 'Using a password' || true
  compose "${FILES[@]}" "${ENVFILE[@]}" restart app
fi

say "waiting for the application"
for _ in $(seq 1 180); do
  state="$(docker inspect -f '{{.State.Health.Status}}' "$APP_CONTAINER" 2>/dev/null || echo starting)"
  [ "$state" = healthy ] && break
  sleep 5
done
if [ "$(docker inspect -f '{{.State.Health.Status}}' "$APP_CONTAINER" 2>/dev/null)" != healthy ]; then
  echo "the application did not become healthy" >&2
  docker logs --tail 100 "$APP_CONTAINER" >&2
  exit 1
fi

say "running the suite"
cd "$HERE"
E2E_PROFILE="$PROFILE" \
E2E_APP_CONTAINER="$APP_CONTAINER" \
E2E_DB_CONTAINER="$DB_CONTAINER" \
E2E_DB_USER="$DB_USER" \
E2E_DB_PASSWORD="$DB_PASSWORD" \
E2E_HTTP_BASE="http://127.0.0.1:${APP_PUBLISHED_PORT:-8080}" \
E2E_HTTPS_BASE="https://127.0.0.1:${E2E_HTTPS_PORT:-8443}" \
E2E_ADMIN_PASSWORD="$ADMIN_PASSWORD" \
E2E_ADMIN_ACTIONS="${ADMIN_ACTIONS_ENABLED:-false}" \
  npx playwright test "${PROJECTS[@]}" "$@"
