#!/usr/bin/env bash
# Bring one profile's stack up and run the end-to-end suite against it.
#
#   ./run.sh local                 # API + deployment shape
#   ./run.sh integration           # ...plus the admin dashboard, over TLS
#   ./run.sh prod                  # the production shape, on a throwaway stack
#
# The admin dashboard only runs under `integration`: it needs TLS in front,
# because its session cookie is `secure` unconditionally, and that is the
# profile whose whole purpose is being pointed at by other people.
#
# Nothing here relaxes a control to make a test pass. The TLS is real TLS with a
# throwaway certificate; each profile runs exactly as it ships.
#
# `integration` and `prod` take their configuration from `.env.<profile>-e2e`,
# which this script generates and which is git-ignored. It deliberately does NOT
# read or write `.env.integration` / `.env.prod`: those are an operator's real
# files, and a test run must not be able to start a real deployment or leave
# throwaway secrets where a real one will pick them up.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY="$(dirname "$HERE")"
PROFILE="${1:-local}"
shift || true

case "$PROFILE" in
  local|integration|prod) ;;
  *) echo "usage: $0 <local|integration|prod> [playwright args]" >&2; exit 2 ;;
esac

say() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }

ADMIN_PASSWORD='e2e-verify-Pass123!'

# A project of this suite's own. The deployment compose files carry
# `name: workin-prod` / `workin-integration`, and without an override `up` here
# would manage *those* containers and reuse their named db-data volume -- on a
# host running the real integration stack, the "throwaway" run would recreate it
# with throwaway secrets. The container names below are derived from the same
# project so nothing has to be kept in step by hand.
PROJECT="workin-e2e-$PROFILE"

compose() { (cd "$DEPLOY" && docker compose -p "$PROJECT" "$@"); }

# ---------------------------------------------------------------- environment
# Every value here is throwaway and fixed, so a run is reproducible. They are
# secrets only in the sense that the application requires them to be set; the
# stack they configure holds the sanitised seed and is destroyed afterwards.
write_env() {
  local path="$DEPLOY/.env.$PROFILE-e2e"
  # Reuse the ports the existing file already fixed. Compose reads them from
  # the file either way; the Playwright base URLs are built from this shell,
  # so without loading them back a second run with custom ports pointed at
  # 8080/8443 -- possibly at something else entirely.
  if [ -f "$path" ] && [ -z "${E2E_REGENERATE_ENV:-}" ]; then
    # Generated at run time by the branch below, so there is nothing to follow.
    set -a
    # shellcheck source=/dev/null
    . "$path"
    set +a
    return
  fi
  cat > "$path" <<ENV
# GENERATED by deploy/e2e/run.sh. Throwaway values for a throwaway stack.
# Not an operator's file: .env.integration and .env.prod are, and this is
# deliberately not either of them.
DB_NAME=workin
DB_USER=workin
DB_PASSWORD=e2e-throwaway-db-password
DB_ROOT_PASSWORD=e2e-throwaway-root-password
JWT_SECRET=e2e-throwaway-signing-secret-not-production-not-integration
ADMIN_PASSWORD=$ADMIN_PASSWORD
ADMIN_ACTIONS_ENABLED=${ADMIN_ACTIONS_ENABLED:-false}
# Only meaningful under integration, and only because a proxy is in front.
FORWARD_HEADERS_STRATEGY=native
APP_PUBLISHED_PORT=${APP_PUBLISHED_PORT:-8080}
DB_PUBLISHED_PORT=${DB_PUBLISHED_PORT:-13306}
E2E_HTTPS_PORT=${E2E_HTTPS_PORT:-8443}
ENV
  # Only production requires WhatsApp credentials, and only production's compose
  # refuses to start without them. Writing them for every profile made the
  # integration stack log "WhatsApp OTP delivery is configured" against a seed
  # derived from real customer data -- exactly what leaving them unset prevents.
  # The deployment-shape suite asserts they are absent outside prod.
  if [ "$PROFILE" = prod ]; then
    cat >> "$path" <<'ENVPROD'
WHATSAPP_API_TOKEN=e2e-throwaway-not-a-real-token
WHATSAPP_INSTANCE_ID=e2e-throwaway-not-a-real-instance
ENVPROD
  fi
  chmod 600 "$path"
}

DB_USER=workin
DB_PASSWORD=workin-local

case "$PROFILE" in
  local)
    FILES=(-f compose.local.yaml)
    ENVFILE=()
    PROJECTS=(--project=api --project=surface --project=deployment)
    ;;
  integration)
    # BEFORE write_env: it expands ADMIN_ACTIONS_ENABLED into the generated
    # file, so setting the default afterwards started the application with
    # actions disabled while telling Playwright they were enabled -- and the
    # administrative-action case then asserted against a company nothing had
    # suspended.
    #
    # The integration profile enables them: there is no legacy PHP admin
    # surface beside this one for ADR-0015 prerequisite 7 to be about.
    : "${ADMIN_ACTIONS_ENABLED:=true}"
    write_env
    FILES=(-f compose.integration.yaml -f e2e/compose.proxy.yaml)
    ENVFILE=(--env-file ".env.$PROFILE-e2e")
    DB_PASSWORD=e2e-throwaway-db-password
    PROJECTS=(--project=api --project=surface --project=deployment --project=admin)
    ;;
  prod)
    write_env
    FILES=(-f compose.prod.yaml)
    ENVFILE=(--env-file ".env.$PROFILE-e2e")
    DB_PASSWORD=e2e-throwaway-db-password
    # Only the deployment shape. compose.prod.yaml mounts NO seed -- production
    # data arrives by a supervised restore, never by a file compose mounts -- so
    # the database is empty and there is nothing for the API journeys to read.
    # Restoring the dev seed into it is what seed_prod below does, when asked.
    PROJECTS=(--project=deployment)
    ;;
esac

APP_CONTAINER="$PROJECT-app-1"
DB_CONTAINER="$PROJECT-db-1"

if [ "$PROFILE" = integration ]; then
  # Outside the repository on purpose. validate_phase0's secret scan walks the
  # working tree, not the index, so a git-ignored key still trips it -- and that
  # is the scan behaving correctly, because its job is to catch a key before it
  # is committed.
  #
  # And not under /tmp. The stack is `restart: unless-stopped`, so it outlives a
  # reboot, but /tmp does not: Docker then recreates the missing bind-mount source
  # as an empty root-owned directory, and the proxy restarts without a certificate
  # until someone with root removes it. The user's state directory survives a
  # reboot and stays the user's. Only this profile has the proxy, so only this
  # profile needs HOME.
  if [ -z "${E2E_TLS_DIR:-}" ]; then
    case "${XDG_STATE_HOME:-}" in
      # The XDG specification says to ignore a relative value; honouring one
      # would put the key under whichever directory this was run from.
      /*) E2E_TLS_DIR="$XDG_STATE_HOME/workin-e2e/tls" ;;
      *)
        if [ -z "${HOME:-}" ]; then
          echo "HOME is not set: set E2E_TLS_DIR to an absolute directory outside the repository" >&2
          exit 1
        fi
        E2E_TLS_DIR="$HOME/.local/state/workin-e2e/tls" ;;
    esac
  fi
  # This script would create a relative one under the directory it was run
  # from, and compose would not look for it there.
  case "$E2E_TLS_DIR" in
    /*) ;;
    *) echo "E2E_TLS_DIR must be an absolute path, not '$E2E_TLS_DIR'" >&2; exit 1 ;;
  esac
  export E2E_TLS_DIR

  say "TLS for the proxy ($E2E_TLS_DIR)"
  # macOS sets TMPDIR with a trailing slash, which would double it in the pattern.
  tmpdir="${TMPDIR:-/tmp}"
  case "$E2E_TLS_DIR" in
    /tmp/* | /var/tmp/* | "${tmpdir%/}"/*)
      echo "warning: $E2E_TLS_DIR is cleared on reboot; the proxy will lose its certificate" >&2 ;;
  esac
  # Docker creates every missing level of a bind-mount source as an empty
  # directory owned by root, so there can be more than one to remove. Walk up to
  # the first directory you can write to, collecting the levels that hold
  # nothing but the next one down. One holding anything else is not Docker's,
  # and nor is one you cannot list: it is not known to be empty.
  docker_made=()
  path="$E2E_TLS_DIR"
  below=""
  until { [ -d "$path" ] && [ -w "$path" ]; } || [ "$path" = / ]; do
    if [ -d "$path" ]; then
      { [ -r "$path" ] && [ -x "$path" ]; } || break
      entries="$(find "$path" -mindepth 1 -maxdepth 1 2>/dev/null || true)"
      [ -z "$entries" ] || [ "$entries" = "$path/$below" ] || break
      docker_made+=("$path")
    fi
    below="$(basename "$path")"
    path="$(dirname "$path")"
  done
  # Removing those levels helps only if the walk reached a directory you can
  # write to. Where it stopped short, at /, at a directory holding other files
  # or at one you cannot list, an empty directory it passed may be a system
  # one, such as /srv.
  if ! { [ -d "$path" ] && [ -w "$path" ]; }; then
    echo "$E2E_TLS_DIR cannot be used: $path is not writable by you, and is not" >&2
    echo "an empty directory Docker left. Choose another E2E_TLS_DIR." >&2
    exit 1
  fi
  if [ "${#docker_made[@]}" -gt 0 ]; then
    echo "$E2E_TLS_DIR is not writable by you. Docker creates each missing level of a" >&2
    echo "bind-mount source as an empty directory owned by root: stop the proxy, run" >&2
    echo "  sudo rmdir$(printf ' "%s"' "${docker_made[@]}")" >&2
    echo "and run this again." >&2
    exit 1
  fi
  mkdir -p "$E2E_TLS_DIR"
  # Resolved once it exists, so that neither a symlink nor `..` carries the key
  # into the checkout.
  checkout="$(cd "$DEPLOY/.." && pwd -P)"
  case "$(cd "$E2E_TLS_DIR" && pwd -P)/" in
    "$checkout"/*)
      echo "E2E_TLS_DIR ($E2E_TLS_DIR) is inside the repository at $checkout, where" >&2
      echo "validate_phase0's secret scan would find the key. Choose a directory outside it." >&2
      exit 1 ;;
  esac
  chmod 700 "$E2E_TLS_DIR"
  if [ ! -f "$E2E_TLS_DIR/server.crt" ] || [ -n "${E2E_REGENERATE_TLS:-}" ]; then
    openssl req -x509 -newkey rsa:2048 -nodes -days 30 \
      -keyout "$E2E_TLS_DIR/server.key" -out "$E2E_TLS_DIR/server.crt" \
      -subj "/CN=localhost" \
      -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" 2>/dev/null
    chmod 644 "$E2E_TLS_DIR/server.crt" "$E2E_TLS_DIR/server.key"
  fi
fi

say "node dependencies"
[ -d "$HERE/node_modules" ] || (cd "$HERE" && npm install --no-audit --no-fund)
# The packages are not the browser. Playwright downloads Chromium separately,
# and every project here drives one, so a clean machine fails at launch without
# this. It is a no-op once the binary is cached.
(cd "$HERE" && npx playwright install chromium)

say "starting the $PROFILE stack"
compose "${FILES[@]}" "${ENVFILE[@]}" up -d --build

if [ "$PROFILE" = prod ] && [ -n "${E2E_SEED_PROD:-}" ]; then
  # Production's compose mounts no seed on purpose. Restoring one by hand is
  # exactly the supervised step the real deployment takes, so doing it here is
  # the honest way to exercise the profile without inventing a shortcut in the
  # compose file that production would then also have.
  say "restoring the sanitised seed by hand (the supervised step, not a mount)"
  until docker exec "$DB_CONTAINER" mariadb -u"$DB_USER" -p"$DB_PASSWORD" \
      -e 'SELECT 1' workin >/dev/null 2>&1; do sleep 3; done
  # The client's exit status survives the filter: `|| true` here would let a
  # syntax error, a full disk or a half-applied dump pass for a restore, and
  # the narrow deployment suite could still go green on the tables that loaded.
  if ! docker exec -i "$DB_CONTAINER" mariadb -u"$DB_USER" -p"$DB_PASSWORD" workin \
      < "$DEPLOY/seed/dev-seed.sql" 2> >(grep -v 'Using a password' >&2); then
    echo "the seed restore failed; not continuing against a half-loaded database" >&2
    exit 1
  fi
  compose "${FILES[@]}" "${ENVFILE[@]}" restart app
fi

say "waiting for the application"
for _ in $(seq 1 180); do
  state="$(docker inspect -f '{{.State.Health.Status}}' "$APP_CONTAINER" 2>/dev/null || echo starting)"
  [ "$state" = healthy ] && break
  sleep 5
done
if [ "$(docker inspect -f '{{.State.Health.Status}}' "$APP_CONTAINER" 2>/dev/null)" != healthy ]; then
  echo "the application did not become healthy" >&2
  docker logs --tail 100 "$APP_CONTAINER" >&2
  exit 1
fi

say "running the suite"
cd "$HERE"
E2E_PROFILE="$PROFILE" \
E2E_APP_CONTAINER="$APP_CONTAINER" \
E2E_DB_CONTAINER="$DB_CONTAINER" \
E2E_DB_USER="$DB_USER" \
E2E_DB_PASSWORD="$DB_PASSWORD" \
E2E_HTTP_BASE="http://127.0.0.1:${APP_PUBLISHED_PORT:-8080}" \
E2E_HTTPS_BASE="https://127.0.0.1:${E2E_HTTPS_PORT:-8443}" \
E2E_ADMIN_PASSWORD="$ADMIN_PASSWORD" \
E2E_ADMIN_ACTIONS="${ADMIN_ACTIONS_ENABLED:-false}" \
  npx playwright test "${PROJECTS[@]}" "$@"
