package com.workin.backend.migration;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.Instant;
import java.time.OffsetDateTime;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import com.workin.backend.AbstractIntegrationTest;

/**
 * Runs the ETL load program emitted by
 * {@code scripts/etl/load_postgres.py} against a real Postgres, with a
 * small representative dump staged by hand.
 *
 * <p>The point is to have the machinery <b>proven before a real dump
 * exists</b>: the load, the durable id mapping, both non-copy
 * transforms, the wall-clock timezone rule, and rerun safety are all
 * exercised here. The only thing missing on the day a dump arrives is
 * the dump.
 *
 * <p>The SQL is generated by invoking the script rather than duplicated
 * here, so the two cannot drift. The {@code copy} section is skipped —
 * {@code \copy} is a psql meta-command — and staging is populated
 * directly instead, which is exactly what that section would have done.
 */
class EtlLoadFixtureTest extends AbstractIntegrationTest {

	private static Path repoRoot;

	@BeforeAll
	static void locateRepoRoot() {
		Path dir = Paths.get("").toAbsolutePath();
		while (dir != null && !Files.exists(dir.resolve("scripts/etl/load_postgres.py"))) {
			dir = dir.getParent();
		}
		repoRoot = dir;
	}

	private static String emit(String section) throws Exception {
		assertThat(repoRoot).as("repository root containing scripts/etl").isNotNull();
		Exception last = null;
		for (String python : new String[] {"python3", "python"}) {
			try {
				Process process = new ProcessBuilder(
						python, "scripts/etl/load_postgres.py", "--section", section)
						.directory(repoRoot.toFile())
						.redirectErrorStream(true)
						.start();
				String out;
				try (InputStream in = process.getInputStream();
						ByteArrayOutputStream buffer = new ByteArrayOutputStream()) {
					in.transferTo(buffer);
					out = buffer.toString(StandardCharsets.UTF_8);
				}
				if (process.waitFor() == 0) {
					return out;
				}
				last = new IllegalStateException(python + " failed: " + out);
			} catch (Exception ex) {
				last = ex;
			}
		}
		throw last;
	}

	private static Connection superuser() throws Exception {
		return DriverManager.getConnection(
				POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
	}

	/**
	 * A miniature dump: one company, two employees, a shift, an exception
	 * type, two punches (one of them a midnight exception day), a
	 * permission row, and the EAV settings chain.
	 *
	 * <p>Each test gets its own migration schema and its own phone numbers.
	 * The suite shares one database, and both the staging tables and the
	 * unique phone columns are global -- without this, a second test
	 * either stages the same legacy id twice or collides on a phone.
	 */
	private static void stageFixture(Statement st, String token) throws Exception {
		st.execute("""
				INSERT INTO migration.stg_companies (id, name, phone, status)
				VALUES ('1', 'Legacy Co', '+2010TOKEN01', 'active');

				INSERT INTO migration.stg_branches (id, company_id, name, is_active)
				VALUES ('7', '1', 'HQ', '1');

				INSERT INTO migration.stg_job_titles (id, company_id, name, work_hours, is_active)
				VALUES ('4', '1', 'Engineer', '7.50', '1');

				INSERT INTO migration.stg_shifts (id, company_id, name, start_time, end_time, days_off, is_active)
				VALUES ('9', '1', 'Day', '09:00:00', '17:00:00', 'Friday,Saturday', '1');

				INSERT INTO migration.stg_exception_types (id, company_id, name)
				VALUES ('3', '1', 'Sick');

				INSERT INTO migration.stg_employees
				  (id, company_id, branch_id, job_title_id, expected_daily_hours, first_name,
				   last_name, phone, password_hash, role, is_active)
				VALUES
				  ('11', '1', '7', '4', '6.00', 'Sara', 'Ali', '+2011TOKEN11', '$2y$hash', 'hr', '1'),
				  ('12', '1', '7', '4', NULL,   'Omar', 'Nabil', '+2012TOKEN22', '$2y$hash2', 'employee', '1');

				-- A real punch, and a midnight exception day.
				INSERT INTO migration.stg_attendance
				  (id, employee_id, check_in, check_out, method, exception_type_id)
				VALUES
				  ('101', '11', '2026-03-02 09:00:00', '2026-03-02 17:00:00', 'app', NULL),
				  ('102', '11', '2026-03-03 00:00:00', NULL, 'app', '3');

				INSERT INTO migration.stg_hr_permissions (id, employee_id)
				VALUES ('55', '11');

				-- The EAV chain: one company setting per definition.
				INSERT INTO migration.stg_setting_definitions (id, setting_key)
				VALUES ('1', 'weekly_off_days'), ('2', 'overtime_rate');

				INSERT INTO migration.stg_setting_allowed_values (id, setting_definition_id, value, sort_order)
				VALUES ('10', '1', 'Friday', '1'), ('11', '1', 'Saturday', '2'), ('20', '2', '150', '1');

				INSERT INTO migration.stg_legacy_company_settings (id, company_id, setting_definition_id)
				VALUES ('300', '1', '1'), ('301', '1', '2');

				INSERT INTO migration.stg_company_setting_values (id, company_setting_id, setting_allowed_value_id)
				VALUES ('400', '300', '10'), ('401', '300', '11'), ('402', '301', '20');
				""".replace("TOKEN", token));
		// The dump's can_* columns arrive with the CSV header; add the two
		// this fixture exercises.
		st.execute("ALTER TABLE migration.stg_hr_permissions ADD COLUMN IF NOT EXISTS can_branches TEXT");
		st.execute("ALTER TABLE migration.stg_hr_permissions ADD COLUMN IF NOT EXISTS can_shifts TEXT");
		st.execute("UPDATE migration.stg_hr_permissions SET can_branches = '1', can_shifts = '0'");
	}

	private static long scalar(Statement st, String sql) throws Exception {
		try (ResultSet rs = st.executeQuery(sql)) {
			rs.next();
			return rs.getLong(1);
		}
	}

	@Test
	void theLoadProgramRunsEndToEndAndIsSafeToRerun() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");
		String finalize = emit("finalize");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "5551");
			st.execute(load);
			st.execute(finalize);

			// --- the durable map exists and covers the FK-referenced entities
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map WHERE entity = 'companies'")).isEqualTo(1);
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map WHERE entity = 'employees'")).isEqualTo(2);
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map WHERE entity = 'attendance'")).isEqualTo(2);
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map WHERE entity = 'tenant_memberships'"))
					.isEqualTo(2);

			// --- foreign keys resolve through the map, not raw legacy ids
			long employeeNewId = scalar(st,
					"SELECT new_id FROM migration.id_map WHERE entity = 'employees' AND legacy_id = 11");
			assertThat(scalar(st,
					"SELECT count(*) FROM attendance WHERE employee_id = " + employeeNewId)).isEqualTo(2);
			// Scoped to the mapped rows: the suite shares one database and
			// other tests create employees of their own.
			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map m ON m.entity = 'employees' AND m.new_id = e.id "
							+ "JOIN companies c ON c.id = e.company_id")).isEqualTo(2);

			// --- the wall-clock rule: the reading is preserved, not shifted
			try (ResultSet rs = st.executeQuery(
					"SELECT check_in FROM attendance a JOIN migration.id_map m "
							+ "ON m.entity = 'attendance' AND m.new_id = a.id WHERE m.legacy_id = 101")) {
				rs.next();
				// PgJDBC will not convert timestamptz straight to Instant.
				assertThat(rs.getObject(1, OffsetDateTime.class).toInstant())
						.isEqualTo(Instant.parse("2026-03-02T09:00:00Z"));
			}
			// --- and the exception day still lands exactly on UTC midnight,
			// which is what keeps isExceptionOnlyRow() recognising it
			assertThat(scalar(st,
					"SELECT count(*) FROM attendance a JOIN migration.id_map m "
							+ "ON m.entity = 'attendance' AND m.new_id = a.id "
							+ "WHERE m.legacy_id = 102 AND a.check_out IS NULL "
							+ "AND a.exception_type_id IS NOT NULL "
							+ "AND a.check_in = TIMESTAMPTZ '2026-03-03 00:00:00+00'")).isEqualTo(1);

			// --- transform 1: EAV collapsed into typed columns, list joined in order
			// Scoped to the migrated company: other tests write their own
			// company_settings rows into the shared database.
			try (ResultSet rs = st.executeQuery(
					"SELECT s.weekly_off_days, s.overtime_rate FROM company_settings s "
							+ "JOIN migration.id_map m ON m.entity = 'companies' AND m.new_id = s.company_id "
							+ "WHERE m.legacy_id = 1")) {
				rs.next();
				assertThat(rs.getString(1)).isEqualTo("Friday,Saturday");
				assertThat(rs.getBigDecimal(2)).isEqualByComparingTo("150");
			}

			// --- transform 2: the granted flag became ALLOW overrides, the
			// ungranted one produced nothing
			assertThat(scalar(st,
					"SELECT count(*) FROM membership_permission_overrides o "
							+ "JOIN permissions p ON p.id = o.permission_id "
							+ "JOIN migration.id_map m ON m.entity = 'tenant_memberships' AND m.new_id = o.membership_id "
							+ "WHERE p.permission_key LIKE 'branches.%' AND o.effect = 'ALLOW'")).isEqualTo(2);
			assertThat(scalar(st,
					"SELECT count(*) FROM membership_permission_overrides o "
							+ "JOIN permissions p ON p.id = o.permission_id "
							+ "JOIN migration.id_map m ON m.entity = 'tenant_memberships' AND m.new_id = o.membership_id "
							+ "WHERE p.permission_key LIKE 'shifts.%'")).isZero();

			// --- counts artifact
			assertThat(scalar(st,
					"SELECT rows FROM migration.load_counts WHERE entity = 'attendance'")).isEqualTo(2);

			// --- the sequence was advanced, so a fresh insert cannot collide
			long freshCompany = scalar(st,
					"INSERT INTO companies (name, phone) VALUES ('Post Cutover', '+20999') RETURNING id");
			assertThat(freshCompany).isGreaterThan(
					scalar(st, "SELECT new_id FROM migration.id_map WHERE entity = 'companies' AND legacy_id = 1"));

			// --- rerun safety: running the whole program again changes nothing
			long attendanceBefore = scalar(st,
					"SELECT count(*) FROM attendance a "
							+ "JOIN migration.id_map m ON m.entity = 'attendance' AND m.new_id = a.id");
			long mapBefore = scalar(st, "SELECT count(*) FROM migration.id_map");
			st.execute(load);
			st.execute(finalize);
			assertThat(scalar(st,
					"SELECT count(*) FROM attendance a "
							+ "JOIN migration.id_map m ON m.entity = 'attendance' AND m.new_id = a.id"))
					.isEqualTo(attendanceBefore);
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map")).isEqualTo(mapBefore);
			assertThat(scalar(st,
					"SELECT count(*) FROM membership_permission_overrides o "
							+ "JOIN migration.id_map m ON m.entity = 'tenant_memberships' "
							+ "AND m.new_id = o.membership_id")).isEqualTo(2);
		}
	}

	@Test
	void anUnmappedPermissionFlagAbortsTheLoad() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "6661");
			// A flag this dump has and PERMISSION_MAP does not.
			st.execute("ALTER TABLE migration.stg_hr_permissions ADD COLUMN can_teleport TEXT");

			assertThat(org.assertj.core.api.Assertions.catchThrowable(() -> st.execute(load)))
					.hasMessageContaining("unmapped hr_permissions flags")
					.hasMessageContaining("can_teleport");
		}
	}

}
