package com.workin.backend.migration;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.Instant;
import java.time.OffsetDateTime;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import com.workin.backend.AbstractIntegrationTest;

/**
 * Runs the ETL load program emitted by
 * {@code scripts/etl/load_postgres.py} against a real Postgres, with a
 * small representative dump staged by hand.
 *
 * <p>The point is to have the machinery <b>proven before a real dump
 * exists</b>: the load, the durable id mapping, both non-copy
 * transforms, the wall-clock timezone rule, and rerun safety are all
 * exercised here. The only thing missing on the day a dump arrives is
 * the dump.
 *
 * <p>The SQL is generated by invoking the script rather than duplicated
 * here, so the two cannot drift. The {@code copy} section is skipped —
 * {@code \copy} is a psql meta-command — and staging is populated
 * directly instead, which is exactly what that section would have done.
 */
class EtlLoadFixtureTest extends AbstractIntegrationTest {

	private static Path repoRoot;

	@BeforeAll
	static void locateRepoRoot() {
		Path dir = Paths.get("").toAbsolutePath();
		while (dir != null && !Files.exists(dir.resolve("scripts/etl/load_postgres.py"))) {
			dir = dir.getParent();
		}
		repoRoot = dir;
	}

	private static String emit(String section) throws Exception {
		assertThat(repoRoot).as("repository root containing scripts/etl").isNotNull();
		Exception last = null;
		for (String python : new String[] {"python3", "python"}) {
			try {
				Process process = new ProcessBuilder(
						python, "scripts/etl/load_postgres.py", "--section", section)
						.directory(repoRoot.toFile())
						.redirectErrorStream(true)
						.start();
				String out;
				try (InputStream in = process.getInputStream();
						ByteArrayOutputStream buffer = new ByteArrayOutputStream()) {
					in.transferTo(buffer);
					out = buffer.toString(StandardCharsets.UTF_8);
				}
				if (process.waitFor() == 0) {
					return out;
				}
				last = new IllegalStateException(python + " failed: " + out);
			} catch (Exception ex) {
				last = ex;
			}
		}
		throw last;
	}

	private static Connection superuser() throws Exception {
		return DriverManager.getConnection(
				POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
	}

	/**
	 * A miniature dump: two companies, four employees -- two of them
	 * sharing a phone across companies, two more sharing a phone within
	 * one company -- a shift, an exception type, two punches (one of them
	 * a midnight exception day), permission rows, a decided request, and
	 * the EAV settings chain.
	 *
	 * <p>Each test gets its own migration schema and its own phone numbers.
	 * The suite shares one database, and both the staging tables and the
	 * unique phone columns are global -- without this, a second test
	 * either stages the same legacy id twice or collides on a phone.
	 *
	 * <p>V44's catalog tables are the same problem in a third place, and
	 * the reason for the TRUNCATE below. Every entity the load writes is
	 * guarded by {@code WHERE NOT EXISTS (... WHERE id = m.new_id)}, which
	 * is only rerun-safe while {@code migration.id_map} survives -- and
	 * every test here drops it with the schema. Fresh ids then clear that
	 * guard while {@code setting_definitions.setting_key}'s own UNIQUE
	 * still holds the previous test's rows, so the second full load in the
	 * suite aborts on a duplicate key. Every other target table survives
	 * this because it has no natural unique key to collide on; it just
	 * accumulates rows, which is why assertions below scope through
	 * {@code migration.id_map} rather than counting a whole table.
	 */
	private static void stageFixture(Statement st, String token) throws Exception {
		st.execute("TRUNCATE setting_allowed_values, setting_definitions RESTART IDENTITY");
		st.execute("""
				INSERT INTO migration.stg_companies (id, name, phone, status, created_at)
				VALUES ('1', 'Legacy Co', '+2010TOKEN01', 'active', '2025-01-15 09:00:00'),
				       ('2', 'Second Co', '+2020TOKEN02', 'active', '2025-02-20 14:30:00');

				-- expires_at is a legacy `datetime`: literal wall clock, loaded as
				-- the same reading in UTC, never shifted. qr_code is a plain
				-- string. Both have target columns and were previously staged or
				-- exported and then dropped.
				INSERT INTO migration.stg_branches
				  (id, company_id, name, is_active, created_at, qr_code, expires_at)
				VALUES ('7', '1', 'HQ', '1', '2025-03-01 10:00:00',
				        'QR-HQ-001', '2027-06-30 23:59:00');

				-- manager_id (11) is the reverse half of the departments/employees
				-- cycle: 11 doesn't have an id yet when departments load, so this
				-- proves the manager_id backfill after employees load.
				INSERT INTO migration.stg_departments (id, company_id, name, manager_id, is_active, created_at)
				VALUES ('20', '1', 'Engineering', '11', '1', '2026-02-01 08:30:00');

				INSERT INTO migration.stg_department_branches (department_id, branch_id)
				VALUES ('20', '7');

				INSERT INTO migration.stg_job_titles
				  (id, company_id, department_id, name, work_hours, is_active, created_at)
				VALUES ('4', '1', '20', 'Engineer', '7.50', '1', '2025-03-02 11:00:00');

				INSERT INTO migration.stg_shifts
				  (id, company_id, name, start_time, end_time, days_off, is_active, created_at)
				VALUES ('9', '1', 'Day', '09:00:00', '17:00:00', 'Friday,Saturday', '1',
				        '2025-03-03 12:00:00');

				INSERT INTO migration.stg_exception_types (id, company_id, name, created_at)
				VALUES ('3', '1', 'Sick', '2025-03-04 13:00:00');

				-- 11 and 12 are each other's own phone anchor. 13 (company 2)
				-- shares 11's phone across companies -- the case identities
				-- exist for. 14 (company 1, same company as 12) shares 12's
				-- phone -- the data-quality duplicate tenant_memberships must
				-- collapse rather than reject.
				-- The six D-036 business fields are staged here too, since the
				-- load must carry them (V42). 11 is the fully-populated row;
				-- 12 holds MySQL zero-dates in BOTH date columns; 13 reuses
				-- 11's employee_code from a DIFFERENT company (which the
				-- per-company UNIQUE must allow); 14 has no code at all.
				-- Between them the three legacy gender enum values are each
				-- represented exactly once.
				INSERT INTO migration.stg_employees
				  (id, company_id, branch_id, department_id, job_title_id, expected_daily_hours, first_name,
				   last_name, phone, password_hash, role, is_active, created_at,
				   employee_code, country_code, national_id, birth_date, gender, hire_date)
				VALUES
				  ('11', '1', '7', '20', '4', '6.00', 'Sara', 'Ali', '+2011TOKEN11', '$2y$hash', 'hr', '1',
				   '2025-04-01 08:00:00',
				   'EMP-001', '+20', '29001011234567', '1990-01-01', 'female', '2020-06-15'),
				  ('12', '1', '7', NULL, '4', NULL,   'Omar', 'Nabil', '+2012TOKEN22', '$2y$hash2', 'employee', '1',
				   '2025-04-02 08:00:00',
				   'EMP-002', NULL, NULL, '0000-00-00', '', '0000-00-00'),
				  ('13', '2', NULL, NULL, NULL, NULL, 'Laila', 'Fathy', '+2011TOKEN11', '$2y$hash3', 'employee', '1',
				   '2025-04-03 08:00:00',
				   'EMP-001', NULL, NULL, NULL, 'male', NULL),
				  ('14', '1', NULL, NULL, NULL, NULL, 'Nabil', 'Omar', '+2012TOKEN22', '$2y$hash4', 'employee', '1',
				   '2025-04-04 08:00:00',
				   NULL, NULL, NULL, NULL, 'other', NULL);

				-- A real punch, and a midnight exception day. created_at is when
				-- the punch was RECORDED; check_in is the wall-clock moment being
				-- recorded. Deliberately different values, so a regression that
				-- conflates the two fails here.
				INSERT INTO migration.stg_attendance
				  (id, employee_id, check_in, check_out, method, exception_type_id, created_at)
				VALUES
				  ('101', '11', '2026-03-02 09:00:00', '2026-03-02 17:00:00', 'app', NULL,
				   '2026-03-02 17:05:00'),
				  ('102', '11', '2026-03-03 00:00:00', NULL, 'app', '3',
				   '2026-03-04 06:30:00');

				INSERT INTO migration.stg_hr_permissions (id, employee_id)
				VALUES ('55', '11'), ('56', '14');

				-- A decided request: exercises approver_id/decided_at/notes,
				-- which the load previously dropped on the floor.
				INSERT INTO migration.stg_request_types (id, company_id, name, created_at)
				VALUES ('1', '1', 'Sick Leave', '2025-05-01 09:00:00');

				INSERT INTO migration.stg_company_official_holidays
				  (id, company_id, name, holiday_date, created_at)
				VALUES ('310', '1', 'Eid', '2026-03-20', '2025-12-01 08:00:00');

				INSERT INTO migration.stg_requests
				  (id, employee_id, request_type_id, from_date, to_date, notes, status, reply,
				   approver_id, decided_at, created_at)
				VALUES
				  ('200', '12', '1', '2026-03-05', '2026-03-05', 'Doctor appointment', 'approved',
				   'Get well soon', '11', '2026-03-04 10:00:00', '2026-03-01 07:45:00');

				-- The payroll group: first fixture coverage of any kind. These
				-- four are in LOAD_ORDER but were never staged, so their load
				-- blocks ran against zero rows until now.
				INSERT INTO migration.stg_salary_contracts
				  (id, employee_id, salary_mode, basic_salary, daily_wage, effective_from, created_at)
				VALUES ('500', '11', 'monthly', '5000.00', '0.00', '2026-01-01',
				        '2025-12-15 10:00:00');

				INSERT INTO migration.stg_payroll_batches
				  (id, company_id, month, year, period_from, period_to, status, created_at)
				VALUES ('90', '1', '3', '2026', '2026-03-01', '2026-03-31', 'finalized',
				        '2026-04-01 12:00:00');

				-- An INSTALLMENTS advance, not the single-month default: the whole
				-- point of carrying the scheduling columns is the case where the
				-- repayment is spread, and a fixture using the default value
				-- would pass even if the columns were still dropped.
				INSERT INTO migration.stg_advances
				  (id, employee_id, amount, remaining, reason, status, request_date, created_at,
				   deduction_mode, deduction_month_count, deduction_amount_per_month,
				   deduction_payroll_year, deduction_payroll_month)
				VALUES ('600', '11', '1000.00', '250.00', 'Emergency', 'approved', '2026-02-10',
				        '2026-02-10 09:30:00',
				        'installments', '4', '250.00', '2026', '3');

				INSERT INTO migration.stg_penalties
				  (id, employee_id, penalty_type, penalty_days, reason, penalty_date,
				   applied_to_payroll, created_at)
				VALUES ('650', '11', 'late', '0.5', 'Late arrival', '2026-02-12', '0',
				        '2026-02-12 11:00:00');

				-- Payroll history and scheduling. payslips hang off batch 90 and
				-- employee 11, which share company 1 -- the agreeing case the
				-- cross-tenant guard permits.
				INSERT INTO migration.stg_payslips
				  (id, batch_id, employee_id, days_present, days_absent, days_leave,
				   overtime_hours, basic_salary, allowances, overtime_pay, net_salary,
				   gross_salary, total_entitlements, total_deductions)
				VALUES ('800', '90', '11', '22', '0', '1', '6.5',
				        '5000.00', '750.00', '203.13', '5953.13',
				        '5953.13', '5953.13', '0.00');

				-- total_days - used_days = 12.5, computed by PostgreSQL rather
				-- than copied: remaining_days is GENERATED on both sides.
				INSERT INTO migration.stg_leave_balance
				  (id, employee_id, year, period_from_month, period_to_month,
				   monthly_cap_days, total_days, used_days, remaining_days)
				VALUES ('900', '11', '2025', '1', '12', '2.50', '21.0', '8.5', '12.5');

				INSERT INTO migration.stg_employee_schedules
				  (id, employee_id, schedule_date, name, start_time, end_time,
				   exception_note, created_at)
				VALUES ('700', '11', '2026-03-02', 'Ramadan', '10:00:00', '16:00:00',
				        'Reduced hours', '2026-02-25 06:15:00');

				INSERT INTO migration.stg_employee_shift_assignments
				  (id, employee_id, shift_id, effective_from, created_at)
				VALUES ('750', '11', '9', '2026-01-01', '2025-12-20 09:00:00');

				-- The EAV chain: one company setting per definition.
				INSERT INTO migration.stg_setting_definitions (id, setting_key)
				VALUES ('1', 'weekly_off_days'), ('2', 'overtime_rate'), ('3', 'pay_overtime');

				INSERT INTO migration.stg_setting_allowed_values (id, setting_definition_id, value, sort_order)
				VALUES ('10', '1', 'Friday', '1'), ('11', '1', 'Saturday', '2'),
				       ('20', '2', '150', '1'), ('30', '3', 'off', '1');

				INSERT INTO migration.stg_legacy_company_settings (id, company_id, setting_definition_id)
				VALUES ('300', '1', '1'), ('301', '1', '2'), ('302', '1', '3');

				INSERT INTO migration.stg_company_setting_values (id, company_setting_id, setting_allowed_value_id)
				VALUES ('400', '300', '10'), ('401', '300', '11'),
				       ('402', '301', '20'), ('403', '302', '30');
				""".replace("TOKEN", token));
		// ddl() already declares every known can_* column; only set the
		// three this fixture exercises, the rest stay NULL (ungranted).
		st.execute("""
				UPDATE migration.stg_hr_permissions SET can_branches = '1', can_shifts = '0'
				WHERE employee_id = '11';
				UPDATE migration.stg_hr_permissions SET can_employees = '1' WHERE employee_id = '14';
				""");
	}

	private static long scalar(Statement st, String sql) throws Exception {
		try (ResultSet rs = st.executeQuery(sql)) {
			rs.next();
			return rs.getLong(1);
		}
	}

	@Test
	void theLoadProgramRunsEndToEndAndIsSafeToRerun() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");
		String finalize = emit("finalize");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "5551");
			st.execute(load);
			st.execute(finalize);

			// --- the durable map exists and covers the FK-referenced entities.
			// 4 employees: 11/12 are their own phone anchors, 13 shares 11's
			// phone from a different company, 14 shares 12's phone from the
			// SAME company (a data-quality duplicate).
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map WHERE entity = 'companies'")).isEqualTo(2);
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map WHERE entity = 'employees'")).isEqualTo(4);
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map WHERE entity = 'attendance'")).isEqualTo(2);
			// One id_map entry per employee, including the two duplicates --
			// hr_permissions needs every legacy employee id resolvable.
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map WHERE entity = 'tenant_memberships'"))
					.isEqualTo(4);
			// Only 2 distinct phones exist, so only 2 identities -- 13 shares
			// 11's, 14 shares 12's, neither mints a new one.
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map WHERE entity = 'identities'")).isEqualTo(2);

			// --- departments: job_titles and employees both resolve
			// department_id, the department-branch pair resolves both parents,
			// and manager_id (a forward reference to an employee that did not
			// have an id yet when departments loaded) is backfilled afterwards.
			assertThat(scalar(st,
					"SELECT count(*) FROM job_titles j "
							+ "JOIN migration.id_map jm ON jm.entity = 'job_titles' AND jm.new_id = j.id "
							+ "JOIN migration.id_map dm ON dm.entity = 'departments' AND dm.new_id = j.department_id "
							+ "WHERE jm.legacy_id = 4 AND dm.legacy_id = 20")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map em ON em.entity = 'employees' AND em.new_id = e.id "
							+ "JOIN migration.id_map dm ON dm.entity = 'departments' AND dm.new_id = e.department_id "
							+ "WHERE em.legacy_id = 11 AND dm.legacy_id = 20")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM departments d "
							+ "JOIN migration.id_map dm ON dm.entity = 'departments' AND dm.new_id = d.id "
							+ "JOIN migration.id_map em ON em.entity = 'employees' AND em.new_id = d.manager_id "
							+ "WHERE dm.legacy_id = 20 AND em.legacy_id = 11 "
							+ "AND d.created_at = TIMESTAMPTZ '2026-02-01 08:30:00+00'")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM department_branches db "
							+ "JOIN migration.id_map dm ON dm.entity = 'departments' AND dm.new_id = db.department_id "
							+ "JOIN migration.id_map bm ON bm.entity = 'branches' AND bm.new_id = db.branch_id "
							+ "JOIN departments d ON d.id = db.department_id AND d.company_id = db.company_id "
							+ "WHERE dm.legacy_id = 20 AND bm.legacy_id = 7")).isEqualTo(1);

			// --- created_at is the legacy instant, not the load clock.
			// Legacy timestamps are true UTC epochs (the settled rule), so
			// the staged wall clock and the stored instant are the same
			// moment. Before this was carried, every migrated row claimed
			// it was created at the cutover instant.
			assertThat(scalar(st,
					"SELECT count(*) FROM companies c "
							+ "JOIN migration.id_map m ON m.entity = 'companies' AND m.new_id = c.id "
							+ "WHERE (m.legacy_id = 1 AND c.created_at = TIMESTAMPTZ '2025-01-15 09:00:00+00') "
							+ "   OR (m.legacy_id = 2 AND c.created_at = TIMESTAMPTZ '2025-02-20 14:30:00+00')"))
					.isEqualTo(2);
			assertThat(scalar(st,
					"SELECT count(*) FROM branches b "
							+ "JOIN migration.id_map m ON m.entity = 'branches' AND m.new_id = b.id "
							+ "WHERE m.legacy_id = 7 AND b.created_at = TIMESTAMPTZ '2025-03-01 10:00:00+00'"))
					.isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM job_titles j "
							+ "JOIN migration.id_map m ON m.entity = 'job_titles' AND m.new_id = j.id "
							+ "WHERE m.legacy_id = 4 AND j.created_at = TIMESTAMPTZ '2025-03-02 11:00:00+00'"))
					.isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM shifts sh "
							+ "JOIN migration.id_map m ON m.entity = 'shifts' AND m.new_id = sh.id "
							+ "WHERE m.legacy_id = 9 AND sh.created_at = TIMESTAMPTZ '2025-03-03 12:00:00+00'"))
					.isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM exception_types et "
							+ "JOIN migration.id_map m ON m.entity = 'exception_types' AND m.new_id = et.id "
							+ "WHERE m.legacy_id = 3 AND et.created_at = TIMESTAMPTZ '2025-03-04 13:00:00+00'"))
					.isEqualTo(1);

			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map m ON m.entity = 'employees' AND m.new_id = e.id "
							+ "WHERE m.legacy_id = 11 AND e.created_at = TIMESTAMPTZ '2025-04-01 08:00:00+00'"))
					.isEqualTo(1);
			// The recorded-at instant is carried AND the wall-clock rule still
			// holds: check_in is untouched, created_at is its own value.
			assertThat(scalar(st,
					"SELECT count(*) FROM attendance a "
							+ "JOIN migration.id_map m ON m.entity = 'attendance' AND m.new_id = a.id "
							+ "WHERE m.legacy_id = 101 "
							+ "AND a.created_at = TIMESTAMPTZ '2026-03-02 17:05:00+00' "
							+ "AND a.check_in = TIMESTAMPTZ '2026-03-02 09:00:00+00'")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM attendance a "
							+ "JOIN migration.id_map m ON m.entity = 'attendance' AND m.new_id = a.id "
							+ "WHERE m.legacy_id = 102 "
							+ "AND a.created_at = TIMESTAMPTZ '2026-03-04 06:30:00+00' "
							+ "AND a.check_in = TIMESTAMPTZ '2026-03-03 00:00:00+00'")).isEqualTo(1);

			assertThat(scalar(st,
					"SELECT count(*) FROM request_types rt "
							+ "JOIN migration.id_map m ON m.entity = 'request_types' AND m.new_id = rt.id "
							+ "WHERE m.legacy_id = 1 AND rt.created_at = TIMESTAMPTZ '2025-05-01 09:00:00+00'"))
					.isEqualTo(1);
			// created_at and decided_at are distinct instants and both survive.
			assertThat(scalar(st,
					"SELECT count(*) FROM requests r "
							+ "JOIN migration.id_map m ON m.entity = 'requests' AND m.new_id = r.id "
							+ "WHERE m.legacy_id = 200 "
							+ "AND r.created_at = TIMESTAMPTZ '2026-03-01 07:45:00+00' "
							+ "AND r.decided_at = TIMESTAMPTZ '2026-03-04 10:00:00+00'")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM company_official_holidays h "
							+ "JOIN migration.id_map m ON m.entity = 'company_official_holidays' "
							+ "AND m.new_id = h.id "
							+ "WHERE m.legacy_id = 310 "
							+ "AND h.created_at = TIMESTAMPTZ '2025-12-01 08:00:00+00' "
							+ "AND h.holiday_date = DATE '2026-03-20'")).isEqualTo(1);

			// --- the payroll group: first fixture coverage, and the batch
			// timestamp the payslips slice will derive from.
			assertThat(scalar(st,
					"SELECT count(*) FROM salary_contracts sc "
							+ "JOIN migration.id_map m ON m.entity = 'salary_contracts' AND m.new_id = sc.id "
							+ "WHERE m.legacy_id = 500 "
							+ "AND sc.created_at = TIMESTAMPTZ '2025-12-15 10:00:00+00' "
							+ "AND sc.salary_mode = 'MONTHLY'")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM payroll_batches b "
							+ "JOIN migration.id_map m ON m.entity = 'payroll_batches' AND m.new_id = b.id "
							+ "WHERE m.legacy_id = 90 "
							+ "AND b.created_at = TIMESTAMPTZ '2026-04-01 12:00:00+00' "
							+ "AND b.status = 'FINALIZED'")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM advances a "
							+ "JOIN migration.id_map m ON m.entity = 'advances' AND m.new_id = a.id "
							+ "WHERE m.legacy_id = 600 "
							+ "AND a.created_at = TIMESTAMPTZ '2026-02-10 09:30:00+00'")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM penalties pn "
							+ "JOIN migration.id_map m ON m.entity = 'penalties' AND m.new_id = pn.id "
							+ "WHERE m.legacy_id = 650 "
							+ "AND pn.created_at = TIMESTAMPTZ '2026-02-12 11:00:00+00'")).isEqualTo(1);

			// --- columns that had a target all along and were dropped anyway.
			// expires_at is a legacy datetime: the same wall-clock reading in
			// UTC, NOT shifted, exactly like attendance.check_in.
			assertThat(scalar(st,
					"SELECT count(*) FROM branches b "
							+ "JOIN migration.id_map m ON m.entity = 'branches' AND m.new_id = b.id "
							+ "WHERE m.legacy_id = 7 AND b.qr_code = 'QR-HQ-001' "
							+ "AND b.expires_at = TIMESTAMPTZ '2027-06-30 23:59:00+00'")).isEqualTo(1);
			// The installment schedule survives: a 1000 advance repaid over 4
			// months at 250 is not a single-month deduction, and loading it as
			// the column default would misstate the arrangement.
			assertThat(scalar(st,
					"SELECT count(*) FROM advances a "
							+ "JOIN migration.id_map m ON m.entity = 'advances' AND m.new_id = a.id "
							+ "WHERE m.legacy_id = 600 "
							+ "AND a.deduction_mode = 'INSTALLMENTS' "
							+ "AND a.deduction_month_count = 4 "
							+ "AND a.deduction_amount_per_month = 250.00 "
							+ "AND a.deduction_payroll_year = 2026 "
							+ "AND a.deduction_payroll_month = 3")).isEqualTo(1);

			// --- payroll history and scheduling: four tables that had a
			// shipped target schema and no migration path at all.
			// payslips: verbatim figures (D-a), company and created_at both
			// derived from the parent batch (D-b).
			assertThat(scalar(st,
					"SELECT count(*) FROM payslips p "
							+ "JOIN migration.id_map m ON m.entity = 'payslips' AND m.new_id = p.id "
							+ "JOIN migration.id_map bm ON bm.entity = 'payroll_batches' AND bm.new_id = p.batch_id "
							+ "JOIN migration.id_map em ON em.entity = 'employees' AND em.new_id = p.employee_id "
							+ "JOIN payroll_batches b ON b.id = p.batch_id AND b.company_id = p.company_id "
							+ "WHERE m.legacy_id = 800 AND bm.legacy_id = 90 AND em.legacy_id = 11 "
							+ "AND p.net_salary = 5953.13 AND p.basic_salary = 5000.00 "
							+ "AND p.created_at = TIMESTAMPTZ '2026-04-01 12:00:00+00'")).isEqualTo(1);
			// leave_balances: remaining_days is computed by PostgreSQL and must
			// equal what MySQL computed; created_at is Jan 1 of its own year.
			assertThat(scalar(st,
					"SELECT count(*) FROM leave_balances lb "
							+ "JOIN migration.id_map m ON m.entity = 'leave_balances' AND m.new_id = lb.id "
							+ "JOIN employees e ON e.id = lb.employee_id AND e.company_id = lb.company_id "
							+ "WHERE m.legacy_id = 900 AND lb.year = 2025 "
							+ "AND lb.total_days = 21.0 AND lb.used_days = 8.5 "
							+ "AND lb.remaining_days = 12.5 "
							+ "AND lb.monthly_cap_days = 2.50 "
							+ "AND lb.created_at = TIMESTAMPTZ '2025-01-01 00:00:00+00'")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM employee_schedules es "
							+ "JOIN migration.id_map m ON m.entity = 'employee_schedules' AND m.new_id = es.id "
							+ "JOIN employees e ON e.id = es.employee_id AND e.company_id = es.company_id "
							+ "WHERE m.legacy_id = 700 AND es.schedule_date = DATE '2026-03-02' "
							+ "AND es.start_time = TIME '10:00:00' "
							+ "AND es.created_at = TIMESTAMPTZ '2026-02-25 06:15:00+00'")).isEqualTo(1);
			// Two foreign keys resolved through the map, and the shift's company
			// agrees with the employee's.
			assertThat(scalar(st,
					"SELECT count(*) FROM employee_shift_assignments a "
							+ "JOIN migration.id_map m ON m.entity = 'employee_shift_assignments' AND m.new_id = a.id "
							+ "JOIN migration.id_map sm ON sm.entity = 'shifts' AND sm.new_id = a.shift_id "
							+ "JOIN shifts sh ON sh.id = a.shift_id AND sh.company_id = a.company_id "
							+ "WHERE m.legacy_id = 750 AND sm.legacy_id = 9 "
							+ "AND a.effective_from = DATE '2026-01-01'")).isEqualTo(1);

			// --- foreign keys resolve through the map, not raw legacy ids
			long employeeNewId = scalar(st,
					"SELECT new_id FROM migration.id_map WHERE entity = 'employees' AND legacy_id = 11");
			assertThat(scalar(st,
					"SELECT count(*) FROM attendance WHERE employee_id = " + employeeNewId)).isEqualTo(2);
			// Scoped to the mapped rows: the suite shares one database and
			// other tests create employees of their own.
			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map m ON m.entity = 'employees' AND m.new_id = e.id "
							+ "JOIN companies c ON c.id = e.company_id")).isEqualTo(4);

			// --- employees.phone is globally UNIQUE: only the phone anchor
			// (11, 12) keeps it on the employees row; the duplicate (13, 14)
			// gets NULL, since the shared phone lives on the identity.
			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map m ON m.entity = 'employees' AND m.new_id = e.id "
							+ "WHERE (m.legacy_id = 11 AND e.phone IS NOT NULL) "
							+ "   OR (m.legacy_id = 13 AND e.phone IS NULL) "
							+ "   OR (m.legacy_id = 12 AND e.phone IS NOT NULL) "
							+ "   OR (m.legacy_id = 14 AND e.phone IS NULL)")).isEqualTo(4);

			// --- tenant_memberships has UNIQUE(identity_id, company_id): 12
			// and 14 (same company, same phone) collapse onto one real row,
			// so 4 employees produce only 3 memberships.
			assertThat(scalar(st,
					"SELECT count(DISTINCT t.id) FROM tenant_memberships t "
							+ "JOIN migration.id_map m ON m.entity = 'tenant_memberships' AND m.new_id = t.id "
							+ "WHERE m.legacy_id IN (11, 12, 13, 14)")).isEqualTo(3);
			assertThat(scalar(st,
					"SELECT count(DISTINCT new_id) FROM migration.id_map "
							+ "WHERE entity = 'tenant_memberships' AND legacy_id IN (12, 14)")).isEqualTo(1);
			// 11 (company 1) and 13 (company 2) get DIFFERENT memberships --
			// one per company -- but the SAME identity, since it's one phone.
			assertThat(scalar(st,
					"SELECT count(DISTINCT new_id) FROM migration.id_map "
							+ "WHERE entity = 'tenant_memberships' AND legacy_id IN (11, 13)")).isEqualTo(2);
			assertThat(scalar(st,
					"SELECT count(DISTINCT t.identity_id) FROM tenant_memberships t "
							+ "JOIN migration.id_map m ON m.entity = 'tenant_memberships' AND m.new_id = t.id "
							+ "WHERE m.legacy_id IN (11, 13)")).isEqualTo(1);

			// --- the wall-clock rule: the reading is preserved, not shifted
			try (ResultSet rs = st.executeQuery(
					"SELECT check_in FROM attendance a JOIN migration.id_map m "
							+ "ON m.entity = 'attendance' AND m.new_id = a.id WHERE m.legacy_id = 101")) {
				rs.next();
				// PgJDBC will not convert timestamptz straight to Instant.
				assertThat(rs.getObject(1, OffsetDateTime.class).toInstant())
						.isEqualTo(Instant.parse("2026-03-02T09:00:00Z"));
			}
			// --- and the exception day still lands exactly on UTC midnight,
			// which is what keeps isExceptionOnlyRow() recognising it
			assertThat(scalar(st,
					"SELECT count(*) FROM attendance a JOIN migration.id_map m "
							+ "ON m.entity = 'attendance' AND m.new_id = a.id "
							+ "WHERE m.legacy_id = 102 AND a.check_out IS NULL "
							+ "AND a.exception_type_id IS NOT NULL "
							+ "AND a.check_in = TIMESTAMPTZ '2026-03-03 00:00:00+00'")).isEqualTo(1);

			// --- transform 1: EAV collapsed into typed columns, list joined in order
			// Scoped to the migrated company: other tests write their own
			// company_settings rows into the shared database.
			try (ResultSet rs = st.executeQuery(
					"SELECT s.weekly_off_days, s.overtime_rate, s.pay_overtime FROM company_settings s "
							+ "JOIN migration.id_map m ON m.entity = 'companies' AND m.new_id = s.company_id "
							+ "WHERE m.legacy_id = 1")) {
				rs.next();
				assertThat(rs.getString(1)).isEqualTo("Friday,Saturday");
				assertThat(rs.getBigDecimal(2)).isEqualByComparingTo("150");
				assertThat(rs.getObject(3, Boolean.class)).isFalse();
			}

			// --- transform 2: the granted flag became ALLOW overrides, the
			// ungranted one produced nothing
			assertThat(scalar(st,
					"SELECT count(*) FROM membership_permission_overrides o "
							+ "JOIN permissions p ON p.id = o.permission_id "
							+ "JOIN migration.id_map m ON m.entity = 'tenant_memberships' AND m.new_id = o.membership_id "
							+ "WHERE p.permission_key LIKE 'branches.%' AND o.effect = 'ALLOW'")).isEqualTo(2);
			assertThat(scalar(st,
					"SELECT count(*) FROM membership_permission_overrides o "
							+ "JOIN permissions p ON p.id = o.permission_id "
							+ "JOIN migration.id_map m ON m.entity = 'tenant_memberships' AND m.new_id = o.membership_id "
							+ "WHERE p.permission_key LIKE 'shifts.%'")).isZero();
			// can_employees (14) resolves through id_map like any other flag,
			// even though 14 shares its membership with 12 -- all 5 keys land
			// on that one shared row.
			assertThat(scalar(st,
					"SELECT count(*) FROM membership_permission_overrides o "
							+ "JOIN migration.id_map m ON m.entity = 'tenant_memberships' AND m.new_id = o.membership_id "
							+ "WHERE m.legacy_id = 14")).isEqualTo(5);

			// --- requests carries approver, decision time and notes, which
			// the load previously dropped: approver_id resolves through the
			// same tenant_memberships map hr_permissions uses.
			try (ResultSet rs = st.executeQuery(
					"SELECT r.notes, r.status, r.decided_at, am.legacy_id AS approver_legacy_id "
							+ "FROM requests r "
							+ "JOIN migration.id_map m ON m.entity = 'requests' AND m.new_id = r.id "
							+ "JOIN migration.id_map am ON am.entity = 'tenant_memberships' "
							+ "     AND am.new_id = r.approver_membership_id "
							+ "WHERE m.legacy_id = 200")) {
				assertThat(rs.next()).isTrue();
				assertThat(rs.getString("notes")).isEqualTo("Doctor appointment");
				assertThat(rs.getString("status")).isEqualTo("APPROVED");
				assertThat(rs.getLong("approver_legacy_id")).isEqualTo(11);
				assertThat(rs.getObject("decided_at", OffsetDateTime.class).toInstant())
						.isEqualTo(Instant.parse("2026-03-04T10:00:00Z"));
			}

			// --- counts artifact: finalize counts the real target table, which
			// is correct for production (empty before cutover) but not for this
			// suite, where every prior test's rows are still sitting in the same
			// shared `attendance` table. Assert it matches a live recount rather
			// than a literal 2, which is what the artifact actually promises.
			long attendanceTotal = scalar(st, "SELECT count(*) FROM attendance");
			assertThat(scalar(st,
					"SELECT rows FROM migration.load_counts WHERE entity = 'attendance'"))
					.isEqualTo(attendanceTotal);

			// Same for the four history/scheduling tables: reconciliation reads
			// migration.load_counts rather than a number scrolling past in a
			// terminal, so each entity must actually have a row there.
			for (String entity : new String[] {
					"payslips", "leave_balances", "employee_schedules",
					"employee_shift_assignments"}) {
				assertThat(scalar(st,
						"SELECT rows FROM migration.load_counts WHERE entity = '" + entity + "'"))
						.as("load_counts row for %s", entity)
						.isEqualTo(scalar(st, "SELECT count(*) FROM " + entity));
			}

			// --- the sequence was advanced, so a fresh insert cannot collide
			long freshCompany = scalar(st,
					"INSERT INTO companies (name, phone) VALUES ('Post Cutover', '+20999') RETURNING id");
			assertThat(freshCompany).isGreaterThan(
					scalar(st, "SELECT new_id FROM migration.id_map WHERE entity = 'companies' AND legacy_id = 1"));

			// --- rerun safety: running the whole program again changes nothing
			long attendanceBefore = scalar(st,
					"SELECT count(*) FROM attendance a "
							+ "JOIN migration.id_map m ON m.entity = 'attendance' AND m.new_id = a.id");
			long mapBefore = scalar(st, "SELECT count(*) FROM migration.id_map");
			long departmentBranchesBefore = scalar(st,
					"SELECT count(*) FROM department_branches db "
							+ "JOIN migration.id_map dm ON dm.entity = 'departments' AND dm.new_id = db.department_id "
							+ "WHERE dm.legacy_id = 20");
			st.execute(load);
			st.execute(finalize);
			assertThat(scalar(st,
					"SELECT count(*) FROM attendance a "
							+ "JOIN migration.id_map m ON m.entity = 'attendance' AND m.new_id = a.id"))
					.isEqualTo(attendanceBefore);
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map")).isEqualTo(mapBefore);
			assertThat(scalar(st,
					"SELECT count(*) FROM department_branches db "
							+ "JOIN migration.id_map dm ON dm.entity = 'departments' AND dm.new_id = db.department_id "
							+ "WHERE dm.legacy_id = 20")).isEqualTo(departmentBranchesBefore);
			// Scoped through the real tables (companies -> tenant_memberships),
			// not id_map directly: 12 and 14 share one membership, so joining
			// id_map straight to the overrides would double-count that row's
			// 5 grants once per legacy id mapped onto it.
			assertThat(scalar(st,
					"SELECT count(*) FROM membership_permission_overrides o "
							+ "JOIN tenant_memberships t ON t.id = o.membership_id "
							+ "JOIN migration.id_map m ON m.entity = 'companies' AND m.new_id = t.company_id "
							+ "WHERE m.legacy_id IN (1, 2)")).isEqualTo(7);
		}
	}

	@Test
	void anUnmappedPermissionFlagAbortsTheLoad() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "6661");
			// A flag this dump has and PERMISSION_MAP does not.
			st.execute("ALTER TABLE migration.stg_hr_permissions ADD COLUMN can_teleport TEXT");

			assertThat(org.assertj.core.api.Assertions.catchThrowable(() -> st.execute(load)))
					.hasMessageContaining("unmapped hr_permissions flags")
					.hasMessageContaining("can_teleport");
		}
	}

	/**
	 * Legacy permits two leave_balance rows for one employee-year; V25's
	 * UNIQUE(employee_id, year) does not, and
	 * duplicate-business-key-analysis.md never examined this table. This is
	 * the failure most likely to actually occur on production data, so the
	 * abort is executed here rather than asserted to exist in the SQL text.
	 */
	@Test
	void aDuplicateLeaveBalanceForOneEmployeeYearAbortsTheLoad() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "7771");
			// A second balance for employee 11, same year as the fixture's.
			st.execute("""
					INSERT INTO migration.stg_leave_balance
					  (id, employee_id, year, period_from_month, period_to_month,
					   monthly_cap_days, total_days, used_days, remaining_days)
					VALUES ('901', '11', '2025', '1', '12', '2.50', '5.0', '1.0', '4.0');
					""");

			assertThat(org.assertj.core.api.Assertions.catchThrowable(() -> st.execute(load)))
					.hasMessageContaining("duplicate (employee_id, year)")
					.hasMessageContaining("11/2025");
		}
	}

	/**
	 * A payslip can reach company_id through its batch or through its
	 * employee. Legacy has no tenant column on payslips to check against,
	 * so if those two disagree the row belongs to neither company
	 * cleanly -- and loading it silently would put one company's payroll
	 * inside another's. Employee 13 belongs to company 2; batch 90 to
	 * company 1.
	 */
	@Test
	void aPayslipWhoseBatchAndEmployeeDisagreeOnCompanyAbortsTheLoad() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "8881");
			st.execute("""
					INSERT INTO migration.stg_payslips
					  (id, batch_id, employee_id, days_present, basic_salary, net_salary)
					VALUES ('801', '90', '13', '20', '3000.00', '3000.00');
					""");

			assertThat(org.assertj.core.api.Assertions.catchThrowable(() -> st.execute(load)))
					.hasMessageContaining("belong to different companies")
					.hasMessageContaining("801");
		}
	}

	/**
	 * Same class of cross-tenant contamination on the scheduling side:
	 * shift 9 belongs to company 1, employee 13 to company 2. The
	 * assignment would otherwise load with the employee's company and a
	 * foreign company's shift.
	 */
	@Test
	void aShiftAssignmentReferencingAnotherCompanysShiftAbortsTheLoad() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "9991");
			st.execute("""
					INSERT INTO migration.stg_employee_shift_assignments
					  (id, employee_id, shift_id, effective_from, created_at)
					VALUES ('751', '13', '9', '2026-01-01', '2025-12-20 09:00:00');
					""");

			assertThat(org.assertj.core.api.Assertions.catchThrowable(() -> st.execute(load)))
					.hasMessageContaining("reference a shift from another company");
		}
	}

	/**
	 * D-036's six employees business fields. V42 added the columns; until
	 * the load populates them they are six columns of NULL on every
	 * migrated row, which reads as "legacy never had this data" rather
	 * than "the load dropped it".
	 *
	 * <p>{@code employee_code} is asserted twice over: preserved verbatim
	 * (D-036 says preserve, do not renumber), and reusable across
	 * companies — 11 and 13 share {@code EMP-001} from different
	 * companies, which V42's {@code UNIQUE (company_id, employee_code)}
	 * must permit and a plain global UNIQUE would reject.
	 */
	@Test
	void employeesCarryTheSixD036BusinessFieldsVerbatim() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "3331");
			st.execute(load);

			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map em ON em.entity = 'employees' AND em.new_id = e.id "
							+ "WHERE em.legacy_id = 11 "
							+ "AND e.employee_code = 'EMP-001' "
							+ "AND e.country_code = '+20' "
							+ "AND e.national_id = '29001011234567' "
							+ "AND e.birth_date = DATE '1990-01-01' "
							+ "AND e.gender = 'female' "
							+ "AND e.hire_date = DATE '2020-06-15'")).isEqualTo(1);

			// The same code in two different companies, both migrated.
			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map em ON em.entity = 'employees' AND em.new_id = e.id "
							+ "WHERE e.employee_code = 'EMP-001'")).isEqualTo(2);
			// 14 had no code in legacy; absent must stay absent, not become ''.
			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map em ON em.entity = 'employees' AND em.new_id = e.id "
							+ "WHERE em.legacy_id = 14 AND e.employee_code IS NULL")).isEqualTo(1);
		}
	}

	/**
	 * Employee 12 carries {@code '0000-00-00'} in both date columns.
	 * Unlike {@code salary_contracts.effective_from} — legacy
	 * {@code NOT NULL}, so a zero-date there must fall back to the row's
	 * own {@code created_at} (D-035/A2) — {@code birth_date} and
	 * {@code hire_date} are nullable in legacy, so NULL is the honest
	 * mapping and D-036 says never invent a date.
	 *
	 * <p>Without a guard on the raw staged text this does not merely
	 * produce a wrong value, it aborts the whole load: PostgreSQL rejects
	 * {@code '0000-00-00'::DATE} outright.
	 *
	 * <p>Employee 11's real dates are asserted in the same test on
	 * purpose. "12's dates are NULL" is true of an unpopulated column
	 * too, so on its own it would pass against a load that carries no
	 * dates at all and prove nothing; pairing it with a row whose dates
	 * must be present is what makes the NULL meaningful.
	 */
	@Test
	void legacyZeroDatesOnEmployeesBecomeNullRatherThanAnInventedDate() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "4441");
			st.execute(load);

			// A row with real dates carries them...
			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map em ON em.entity = 'employees' AND em.new_id = e.id "
							+ "WHERE em.legacy_id = 11 "
							+ "AND e.birth_date = DATE '1990-01-01' "
							+ "AND e.hire_date = DATE '2020-06-15'")).isEqualTo(1);
			// ...and only then does the zero-date row's NULL mean anything.
			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map em ON em.entity = 'employees' AND em.new_id = e.id "
							+ "WHERE em.legacy_id = 12 "
							+ "AND e.birth_date IS NULL AND e.hire_date IS NULL")).isEqualTo(1);

			// Specifically NOT the created_at fallback effective_from uses:
			// no employee may end up dated by when its row was created.
			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map em ON em.entity = 'employees' AND em.new_id = e.id "
							+ "WHERE e.hire_date = DATE '2025-04-02'")).isEqualTo(0);
		}
	}

	/**
	 * Legacy {@code gender} is {@code enum('male','female','other')},
	 * mapped 1:1 by value (D-036) against V42's CHECK, which mirrors the
	 * enum exactly. Employee 12 holds {@code ''} — what MySQL stores for
	 * an invalid enum value in non-strict mode, and a value V42's CHECK
	 * rejects. It maps to NULL ("no gender recorded"), the only mapping
	 * that neither invents a gender nor aborts the load.
	 */
	@Test
	void everyLegacyGenderValueMapsOneToOneAndTheEmptyPlaceholderBecomesNull() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "2221");
			st.execute(load);

			String scoped = "SELECT count(*) FROM employees e "
					+ "JOIN migration.id_map em ON em.entity = 'employees' AND em.new_id = e.id "
					+ "WHERE e.gender = ";
			assertThat(scalar(st, scoped + "'female'")).isEqualTo(1);
			assertThat(scalar(st, scoped + "'male'")).isEqualTo(1);
			assertThat(scalar(st, scoped + "'other'")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map em ON em.entity = 'employees' AND em.new_id = e.id "
							+ "WHERE em.legacy_id = 12 AND e.gender IS NULL")).isEqualTo(1);
		}
	}

	/**
	 * Every decision that repairs a value requires the repair to be
	 * recorded — A2 "so the synthesized value remains traceable", A3
	 * "record each repair individually", A5 by explicit reuse of A2's
	 * rule, D-036 "with the remediation recorded". Until now there was
	 * nowhere to record one, so five shipped repairs silently discarded
	 * the value they replaced.
	 *
	 * <p>The log lives in the {@code migration} schema beside
	 * {@code id_map} and {@code load_counts}, so it is dropped with them
	 * per test — assertions here need no id-map scoping, unlike every
	 * target-table assertion above.
	 *
	 * <p>Asserting {@code original} is the whole point. A log that
	 * recorded only "birth_date was repaired" would satisfy the letter of
	 * "record the remediation" while losing the one thing nothing else in
	 * the system still holds: what legacy actually had.
	 */
	@Test
	void everyD036RepairIsRecordedWithTheOriginalLegacyValue() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "6665");
			st.execute(load);

			// Employee 12: both zero-dates and the '' gender placeholder.
			assertThat(scalar(st,
					"SELECT count(*) FROM migration.remediation_log "
							+ "WHERE entity = 'employees' AND legacy_id = 12 "
							+ "AND column_name = 'birth_date' "
							+ "AND original = '0000-00-00' AND applied IS NULL "
							+ "AND decision_ref = 'D-036'")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM migration.remediation_log "
							+ "WHERE entity = 'employees' AND legacy_id = 12 "
							+ "AND column_name = 'hire_date' "
							+ "AND original = '0000-00-00' AND applied IS NULL "
							+ "AND decision_ref = 'D-036'")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM migration.remediation_log "
							+ "WHERE entity = 'employees' AND legacy_id = 12 "
							+ "AND column_name = 'gender' "
							+ "AND original = '' AND applied IS NULL "
							+ "AND decision_ref = 'D-036'")).isEqualTo(1);

			// Employee 11 carries real values in all three; a repair logged
			// for it would mean the predicate is matching healthy rows.
			assertThat(scalar(st,
					"SELECT count(*) FROM migration.remediation_log "
							+ "WHERE entity = 'employees' AND legacy_id = 11")).isEqualTo(0);
		}
	}

	/**
	 * A2 is the one repair that invents a value rather than clearing one:
	 * a zero-date {@code effective_from} becomes the row's own
	 * {@code created_at}, because legacy declares the column NOT NULL.
	 * That makes the record more important here than anywhere else — the
	 * loaded date looks entirely ordinary, and without the log nothing
	 * distinguishes it from a date legacy really held.
	 */
	@Test
	void theSynthesizedEffectiveFromIsRecordedSoTheFallbackStaysTraceable() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "6662");
			st.execute("""
					INSERT INTO migration.stg_salary_contracts
					  (id, employee_id, salary_mode, basic_salary, daily_wage, effective_from, created_at)
					VALUES ('501', '11', 'monthly', '7000.00', '0.00', '0000-00-00',
					        '2025-11-20 10:00:00');

					INSERT INTO migration.stg_employee_shift_assignments
					  (id, employee_id, shift_id, effective_from, created_at)
					VALUES ('752', '11', '9', '0000-00-00', '2025-10-05 08:00:00');
					""");
			st.execute(load);

			// The repaired row loaded with the fallback...
			assertThat(scalar(st,
					"SELECT count(*) FROM salary_contracts c "
							+ "JOIN migration.id_map cm ON cm.entity = 'salary_contracts' "
							+ "AND cm.new_id = c.id "
							+ "WHERE cm.legacy_id = 501 "
							+ "AND c.effective_from = DATE '2025-11-20'")).isEqualTo(1);
			// ...and the log says where that date came from.
			assertThat(scalar(st,
					"SELECT count(*) FROM migration.remediation_log "
							+ "WHERE entity = 'salary_contracts' AND legacy_id = 501 "
							+ "AND column_name = 'effective_from' "
							+ "AND original = '0000-00-00' AND applied = '2025-11-20' "
							+ "AND decision_ref = 'D-035/A2'")).isEqualTo(1);

			// A5 reuses A2's rule rather than inventing a second one, so it
			// records the same way, under its own decision.
			assertThat(scalar(st,
					"SELECT count(*) FROM migration.remediation_log "
							+ "WHERE entity = 'employee_shift_assignments' AND legacy_id = 752 "
							+ "AND column_name = 'effective_from' "
							+ "AND original = '0000-00-00' AND applied = '2025-10-05' "
							+ "AND decision_ref = 'D-035/A5'")).isEqualTo(1);

			// Contract 500 has a real date and must not be logged.
			assertThat(scalar(st,
					"SELECT count(*) FROM migration.remediation_log "
							+ "WHERE entity = 'salary_contracts' AND legacy_id = 500")).isEqualTo(0);
		}
	}

	/**
	 * A3 says "record each repair individually" — a count of how many
	 * attendance rows were repaired is what {@code load_counts} already
	 * does and is explicitly not what A3 asked for. Row 103 holds real
	 * punches and an exception day at once; the load keeps the punches
	 * and clears the exception, so the exception is the value that
	 * disappears and therefore the one that must be recorded.
	 */
	@Test
	void eachAttendanceXorRepairIsRecordedIndividually() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "6663");
			st.execute("""
					INSERT INTO migration.stg_attendance
					  (id, employee_id, check_in, check_out, method, exception_type_id, created_at)
					VALUES ('103', '11', '2026-03-06 09:00:00', '2026-03-06 17:00:00', 'app', '3',
					        '2026-03-06 17:10:00');
					""");
			st.execute(load);

			assertThat(scalar(st,
					"SELECT count(*) FROM migration.remediation_log "
							+ "WHERE entity = 'attendance' AND legacy_id = 103 "
							+ "AND column_name = 'exception_type_id' "
							+ "AND original = '3' AND applied IS NULL "
							+ "AND decision_ref = 'D-035/A3'")).isEqualTo(1);

			// 102 is the legal exception-only row: exception, no check_out.
			// Repairing or logging it would be the regression.
			assertThat(scalar(st,
					"SELECT count(*) FROM migration.remediation_log "
							+ "WHERE entity = 'attendance' AND legacy_id = 102")).isEqualTo(0);
		}
	}

	/**
	 * The log must not grow on a rerun. Deliberately not guarded the way
	 * every target table is — {@code WHERE NOT EXISTS (... id = m.new_id)}
	 * is only rerun-safe while {@code migration.id_map} survives, which is
	 * the defect this suite hit on 2026-08-15 and issue #99 records. The
	 * log keys on business identity instead: an entity, a legacy id and a
	 * column name identify a repaired cell without consulting the map at
	 * all.
	 */
	@Test
	void theRemediationLogDoesNotGrowWhenTheLoadIsRerun() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "6664");
			st.execute(load);

			long first = scalar(st, "SELECT count(*) FROM migration.remediation_log");
			assertThat(first).isGreaterThan(0);

			st.execute(load);

			assertThat(scalar(st, "SELECT count(*) FROM migration.remediation_log"))
					.isEqualTo(first);
			// And specifically not two rows for the same repaired cell.
			assertThat(scalar(st,
					"SELECT count(*) FROM migration.remediation_log "
							+ "WHERE entity = 'employees' AND legacy_id = 12 "
							+ "AND column_name = 'birth_date'")).isEqualTo(1);
		}
	}

}
