package com.workin.backend.migration;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.Instant;
import java.time.OffsetDateTime;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import com.workin.backend.AbstractIntegrationTest;

/**
 * Runs the ETL load program emitted by
 * {@code scripts/etl/load_postgres.py} against a real Postgres, with a
 * small representative dump staged by hand.
 *
 * <p>The point is to have the machinery <b>proven before a real dump
 * exists</b>: the load, the durable id mapping, both non-copy
 * transforms, the wall-clock timezone rule, and rerun safety are all
 * exercised here. The only thing missing on the day a dump arrives is
 * the dump.
 *
 * <p>The SQL is generated by invoking the script rather than duplicated
 * here, so the two cannot drift. The {@code copy} section is skipped —
 * {@code \copy} is a psql meta-command — and staging is populated
 * directly instead, which is exactly what that section would have done.
 */
class EtlLoadFixtureTest extends AbstractIntegrationTest {

	private static Path repoRoot;

	@BeforeAll
	static void locateRepoRoot() {
		Path dir = Paths.get("").toAbsolutePath();
		while (dir != null && !Files.exists(dir.resolve("scripts/etl/load_postgres.py"))) {
			dir = dir.getParent();
		}
		repoRoot = dir;
	}

	private static String emit(String section) throws Exception {
		assertThat(repoRoot).as("repository root containing scripts/etl").isNotNull();
		Exception last = null;
		for (String python : new String[] {"python3", "python"}) {
			try {
				Process process = new ProcessBuilder(
						python, "scripts/etl/load_postgres.py", "--section", section)
						.directory(repoRoot.toFile())
						.redirectErrorStream(true)
						.start();
				String out;
				try (InputStream in = process.getInputStream();
						ByteArrayOutputStream buffer = new ByteArrayOutputStream()) {
					in.transferTo(buffer);
					out = buffer.toString(StandardCharsets.UTF_8);
				}
				if (process.waitFor() == 0) {
					return out;
				}
				last = new IllegalStateException(python + " failed: " + out);
			} catch (Exception ex) {
				last = ex;
			}
		}
		throw last;
	}

	private static Connection superuser() throws Exception {
		return DriverManager.getConnection(
				POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
	}

	/**
	 * A miniature dump: two companies, four employees -- two of them
	 * sharing a phone across companies, two more sharing a phone within
	 * one company -- a shift, an exception type, two punches (one of them
	 * a midnight exception day), permission rows, a decided request, and
	 * the EAV settings chain.
	 *
	 * <p>Each test gets its own migration schema and its own phone numbers.
	 * The suite shares one database, and both the staging tables and the
	 * unique phone columns are global -- without this, a second test
	 * either stages the same legacy id twice or collides on a phone.
	 */
	private static void stageFixture(Statement st, String token) throws Exception {
		st.execute("""
				INSERT INTO migration.stg_companies (id, name, phone, status, created_at)
				VALUES ('1', 'Legacy Co', '+2010TOKEN01', 'active', '2025-01-15 09:00:00'),
				       ('2', 'Second Co', '+2020TOKEN02', 'active', '2025-02-20 14:30:00');

				INSERT INTO migration.stg_branches (id, company_id, name, is_active, created_at)
				VALUES ('7', '1', 'HQ', '1', '2025-03-01 10:00:00');

				-- manager_id (11) is the reverse half of the departments/employees
				-- cycle: 11 doesn't have an id yet when departments load, so this
				-- proves the manager_id backfill after employees load.
				INSERT INTO migration.stg_departments (id, company_id, name, manager_id, is_active, created_at)
				VALUES ('20', '1', 'Engineering', '11', '1', '2026-02-01 08:30:00');

				INSERT INTO migration.stg_department_branches (department_id, branch_id)
				VALUES ('20', '7');

				INSERT INTO migration.stg_job_titles
				  (id, company_id, department_id, name, work_hours, is_active, created_at)
				VALUES ('4', '1', '20', 'Engineer', '7.50', '1', '2025-03-02 11:00:00');

				INSERT INTO migration.stg_shifts
				  (id, company_id, name, start_time, end_time, days_off, is_active, created_at)
				VALUES ('9', '1', 'Day', '09:00:00', '17:00:00', 'Friday,Saturday', '1',
				        '2025-03-03 12:00:00');

				INSERT INTO migration.stg_exception_types (id, company_id, name, created_at)
				VALUES ('3', '1', 'Sick', '2025-03-04 13:00:00');

				-- 11 and 12 are each other's own phone anchor. 13 (company 2)
				-- shares 11's phone across companies -- the case identities
				-- exist for. 14 (company 1, same company as 12) shares 12's
				-- phone -- the data-quality duplicate tenant_memberships must
				-- collapse rather than reject.
				INSERT INTO migration.stg_employees
				  (id, company_id, branch_id, department_id, job_title_id, expected_daily_hours, first_name,
				   last_name, phone, password_hash, role, is_active, created_at)
				VALUES
				  ('11', '1', '7', '20', '4', '6.00', 'Sara', 'Ali', '+2011TOKEN11', '$2y$hash', 'hr', '1',
				   '2025-04-01 08:00:00'),
				  ('12', '1', '7', NULL, '4', NULL,   'Omar', 'Nabil', '+2012TOKEN22', '$2y$hash2', 'employee', '1',
				   '2025-04-02 08:00:00'),
				  ('13', '2', NULL, NULL, NULL, NULL, 'Laila', 'Fathy', '+2011TOKEN11', '$2y$hash3', 'employee', '1',
				   '2025-04-03 08:00:00'),
				  ('14', '1', NULL, NULL, NULL, NULL, 'Nabil', 'Omar', '+2012TOKEN22', '$2y$hash4', 'employee', '1',
				   '2025-04-04 08:00:00');

				-- A real punch, and a midnight exception day. created_at is when
				-- the punch was RECORDED; check_in is the wall-clock moment being
				-- recorded. Deliberately different values, so a regression that
				-- conflates the two fails here.
				INSERT INTO migration.stg_attendance
				  (id, employee_id, check_in, check_out, method, exception_type_id, created_at)
				VALUES
				  ('101', '11', '2026-03-02 09:00:00', '2026-03-02 17:00:00', 'app', NULL,
				   '2026-03-02 17:05:00'),
				  ('102', '11', '2026-03-03 00:00:00', NULL, 'app', '3',
				   '2026-03-04 06:30:00');

				INSERT INTO migration.stg_hr_permissions (id, employee_id)
				VALUES ('55', '11'), ('56', '14');

				-- A decided request: exercises approver_id/decided_at/notes,
				-- which the load previously dropped on the floor.
				INSERT INTO migration.stg_request_types (id, company_id, name, created_at)
				VALUES ('1', '1', 'Sick Leave', '2025-05-01 09:00:00');

				INSERT INTO migration.stg_company_official_holidays
				  (id, company_id, name, holiday_date, created_at)
				VALUES ('310', '1', 'Eid', '2026-03-20', '2025-12-01 08:00:00');

				INSERT INTO migration.stg_requests
				  (id, employee_id, request_type_id, from_date, to_date, notes, status, reply,
				   approver_id, decided_at, created_at)
				VALUES
				  ('200', '12', '1', '2026-03-05', '2026-03-05', 'Doctor appointment', 'approved',
				   'Get well soon', '11', '2026-03-04 10:00:00', '2026-03-01 07:45:00');

				-- The EAV chain: one company setting per definition.
				INSERT INTO migration.stg_setting_definitions (id, setting_key)
				VALUES ('1', 'weekly_off_days'), ('2', 'overtime_rate'), ('3', 'pay_overtime');

				INSERT INTO migration.stg_setting_allowed_values (id, setting_definition_id, value, sort_order)
				VALUES ('10', '1', 'Friday', '1'), ('11', '1', 'Saturday', '2'),
				       ('20', '2', '150', '1'), ('30', '3', 'off', '1');

				INSERT INTO migration.stg_legacy_company_settings (id, company_id, setting_definition_id)
				VALUES ('300', '1', '1'), ('301', '1', '2'), ('302', '1', '3');

				INSERT INTO migration.stg_company_setting_values (id, company_setting_id, setting_allowed_value_id)
				VALUES ('400', '300', '10'), ('401', '300', '11'),
				       ('402', '301', '20'), ('403', '302', '30');
				""".replace("TOKEN", token));
		// ddl() already declares every known can_* column; only set the
		// three this fixture exercises, the rest stay NULL (ungranted).
		st.execute("""
				UPDATE migration.stg_hr_permissions SET can_branches = '1', can_shifts = '0'
				WHERE employee_id = '11';
				UPDATE migration.stg_hr_permissions SET can_employees = '1' WHERE employee_id = '14';
				""");
	}

	private static long scalar(Statement st, String sql) throws Exception {
		try (ResultSet rs = st.executeQuery(sql)) {
			rs.next();
			return rs.getLong(1);
		}
	}

	@Test
	void theLoadProgramRunsEndToEndAndIsSafeToRerun() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");
		String finalize = emit("finalize");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "5551");
			st.execute(load);
			st.execute(finalize);

			// --- the durable map exists and covers the FK-referenced entities.
			// 4 employees: 11/12 are their own phone anchors, 13 shares 11's
			// phone from a different company, 14 shares 12's phone from the
			// SAME company (a data-quality duplicate).
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map WHERE entity = 'companies'")).isEqualTo(2);
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map WHERE entity = 'employees'")).isEqualTo(4);
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map WHERE entity = 'attendance'")).isEqualTo(2);
			// One id_map entry per employee, including the two duplicates --
			// hr_permissions needs every legacy employee id resolvable.
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map WHERE entity = 'tenant_memberships'"))
					.isEqualTo(4);
			// Only 2 distinct phones exist, so only 2 identities -- 13 shares
			// 11's, 14 shares 12's, neither mints a new one.
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map WHERE entity = 'identities'")).isEqualTo(2);

			// --- departments: job_titles and employees both resolve
			// department_id, the department-branch pair resolves both parents,
			// and manager_id (a forward reference to an employee that did not
			// have an id yet when departments loaded) is backfilled afterwards.
			assertThat(scalar(st,
					"SELECT count(*) FROM job_titles j "
							+ "JOIN migration.id_map jm ON jm.entity = 'job_titles' AND jm.new_id = j.id "
							+ "JOIN migration.id_map dm ON dm.entity = 'departments' AND dm.new_id = j.department_id "
							+ "WHERE jm.legacy_id = 4 AND dm.legacy_id = 20")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map em ON em.entity = 'employees' AND em.new_id = e.id "
							+ "JOIN migration.id_map dm ON dm.entity = 'departments' AND dm.new_id = e.department_id "
							+ "WHERE em.legacy_id = 11 AND dm.legacy_id = 20")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM departments d "
							+ "JOIN migration.id_map dm ON dm.entity = 'departments' AND dm.new_id = d.id "
							+ "JOIN migration.id_map em ON em.entity = 'employees' AND em.new_id = d.manager_id "
							+ "WHERE dm.legacy_id = 20 AND em.legacy_id = 11 "
							+ "AND d.created_at = TIMESTAMPTZ '2026-02-01 08:30:00+00'")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM department_branches db "
							+ "JOIN migration.id_map dm ON dm.entity = 'departments' AND dm.new_id = db.department_id "
							+ "JOIN migration.id_map bm ON bm.entity = 'branches' AND bm.new_id = db.branch_id "
							+ "JOIN departments d ON d.id = db.department_id AND d.company_id = db.company_id "
							+ "WHERE dm.legacy_id = 20 AND bm.legacy_id = 7")).isEqualTo(1);

			// --- created_at is the legacy instant, not the load clock.
			// Legacy timestamps are true UTC epochs (the settled rule), so
			// the staged wall clock and the stored instant are the same
			// moment. Before this was carried, every migrated row claimed
			// it was created at the cutover instant.
			assertThat(scalar(st,
					"SELECT count(*) FROM companies c "
							+ "JOIN migration.id_map m ON m.entity = 'companies' AND m.new_id = c.id "
							+ "WHERE (m.legacy_id = 1 AND c.created_at = TIMESTAMPTZ '2025-01-15 09:00:00+00') "
							+ "   OR (m.legacy_id = 2 AND c.created_at = TIMESTAMPTZ '2025-02-20 14:30:00+00')"))
					.isEqualTo(2);
			assertThat(scalar(st,
					"SELECT count(*) FROM branches b "
							+ "JOIN migration.id_map m ON m.entity = 'branches' AND m.new_id = b.id "
							+ "WHERE m.legacy_id = 7 AND b.created_at = TIMESTAMPTZ '2025-03-01 10:00:00+00'"))
					.isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM job_titles j "
							+ "JOIN migration.id_map m ON m.entity = 'job_titles' AND m.new_id = j.id "
							+ "WHERE m.legacy_id = 4 AND j.created_at = TIMESTAMPTZ '2025-03-02 11:00:00+00'"))
					.isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM shifts sh "
							+ "JOIN migration.id_map m ON m.entity = 'shifts' AND m.new_id = sh.id "
							+ "WHERE m.legacy_id = 9 AND sh.created_at = TIMESTAMPTZ '2025-03-03 12:00:00+00'"))
					.isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM exception_types et "
							+ "JOIN migration.id_map m ON m.entity = 'exception_types' AND m.new_id = et.id "
							+ "WHERE m.legacy_id = 3 AND et.created_at = TIMESTAMPTZ '2025-03-04 13:00:00+00'"))
					.isEqualTo(1);

			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map m ON m.entity = 'employees' AND m.new_id = e.id "
							+ "WHERE m.legacy_id = 11 AND e.created_at = TIMESTAMPTZ '2025-04-01 08:00:00+00'"))
					.isEqualTo(1);
			// The recorded-at instant is carried AND the wall-clock rule still
			// holds: check_in is untouched, created_at is its own value.
			assertThat(scalar(st,
					"SELECT count(*) FROM attendance a "
							+ "JOIN migration.id_map m ON m.entity = 'attendance' AND m.new_id = a.id "
							+ "WHERE m.legacy_id = 101 "
							+ "AND a.created_at = TIMESTAMPTZ '2026-03-02 17:05:00+00' "
							+ "AND a.check_in = TIMESTAMPTZ '2026-03-02 09:00:00+00'")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM attendance a "
							+ "JOIN migration.id_map m ON m.entity = 'attendance' AND m.new_id = a.id "
							+ "WHERE m.legacy_id = 102 "
							+ "AND a.created_at = TIMESTAMPTZ '2026-03-04 06:30:00+00' "
							+ "AND a.check_in = TIMESTAMPTZ '2026-03-03 00:00:00+00'")).isEqualTo(1);

			assertThat(scalar(st,
					"SELECT count(*) FROM request_types rt "
							+ "JOIN migration.id_map m ON m.entity = 'request_types' AND m.new_id = rt.id "
							+ "WHERE m.legacy_id = 1 AND rt.created_at = TIMESTAMPTZ '2025-05-01 09:00:00+00'"))
					.isEqualTo(1);
			// created_at and decided_at are distinct instants and both survive.
			assertThat(scalar(st,
					"SELECT count(*) FROM requests r "
							+ "JOIN migration.id_map m ON m.entity = 'requests' AND m.new_id = r.id "
							+ "WHERE m.legacy_id = 200 "
							+ "AND r.created_at = TIMESTAMPTZ '2026-03-01 07:45:00+00' "
							+ "AND r.decided_at = TIMESTAMPTZ '2026-03-04 10:00:00+00'")).isEqualTo(1);
			assertThat(scalar(st,
					"SELECT count(*) FROM company_official_holidays h "
							+ "JOIN migration.id_map m ON m.entity = 'company_official_holidays' "
							+ "AND m.new_id = h.id "
							+ "WHERE m.legacy_id = 310 "
							+ "AND h.created_at = TIMESTAMPTZ '2025-12-01 08:00:00+00' "
							+ "AND h.holiday_date = DATE '2026-03-20'")).isEqualTo(1);

			// --- foreign keys resolve through the map, not raw legacy ids
			long employeeNewId = scalar(st,
					"SELECT new_id FROM migration.id_map WHERE entity = 'employees' AND legacy_id = 11");
			assertThat(scalar(st,
					"SELECT count(*) FROM attendance WHERE employee_id = " + employeeNewId)).isEqualTo(2);
			// Scoped to the mapped rows: the suite shares one database and
			// other tests create employees of their own.
			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map m ON m.entity = 'employees' AND m.new_id = e.id "
							+ "JOIN companies c ON c.id = e.company_id")).isEqualTo(4);

			// --- employees.phone is globally UNIQUE: only the phone anchor
			// (11, 12) keeps it on the employees row; the duplicate (13, 14)
			// gets NULL, since the shared phone lives on the identity.
			assertThat(scalar(st,
					"SELECT count(*) FROM employees e "
							+ "JOIN migration.id_map m ON m.entity = 'employees' AND m.new_id = e.id "
							+ "WHERE (m.legacy_id = 11 AND e.phone IS NOT NULL) "
							+ "   OR (m.legacy_id = 13 AND e.phone IS NULL) "
							+ "   OR (m.legacy_id = 12 AND e.phone IS NOT NULL) "
							+ "   OR (m.legacy_id = 14 AND e.phone IS NULL)")).isEqualTo(4);

			// --- tenant_memberships has UNIQUE(identity_id, company_id): 12
			// and 14 (same company, same phone) collapse onto one real row,
			// so 4 employees produce only 3 memberships.
			assertThat(scalar(st,
					"SELECT count(DISTINCT t.id) FROM tenant_memberships t "
							+ "JOIN migration.id_map m ON m.entity = 'tenant_memberships' AND m.new_id = t.id "
							+ "WHERE m.legacy_id IN (11, 12, 13, 14)")).isEqualTo(3);
			assertThat(scalar(st,
					"SELECT count(DISTINCT new_id) FROM migration.id_map "
							+ "WHERE entity = 'tenant_memberships' AND legacy_id IN (12, 14)")).isEqualTo(1);
			// 11 (company 1) and 13 (company 2) get DIFFERENT memberships --
			// one per company -- but the SAME identity, since it's one phone.
			assertThat(scalar(st,
					"SELECT count(DISTINCT new_id) FROM migration.id_map "
							+ "WHERE entity = 'tenant_memberships' AND legacy_id IN (11, 13)")).isEqualTo(2);
			assertThat(scalar(st,
					"SELECT count(DISTINCT t.identity_id) FROM tenant_memberships t "
							+ "JOIN migration.id_map m ON m.entity = 'tenant_memberships' AND m.new_id = t.id "
							+ "WHERE m.legacy_id IN (11, 13)")).isEqualTo(1);

			// --- the wall-clock rule: the reading is preserved, not shifted
			try (ResultSet rs = st.executeQuery(
					"SELECT check_in FROM attendance a JOIN migration.id_map m "
							+ "ON m.entity = 'attendance' AND m.new_id = a.id WHERE m.legacy_id = 101")) {
				rs.next();
				// PgJDBC will not convert timestamptz straight to Instant.
				assertThat(rs.getObject(1, OffsetDateTime.class).toInstant())
						.isEqualTo(Instant.parse("2026-03-02T09:00:00Z"));
			}
			// --- and the exception day still lands exactly on UTC midnight,
			// which is what keeps isExceptionOnlyRow() recognising it
			assertThat(scalar(st,
					"SELECT count(*) FROM attendance a JOIN migration.id_map m "
							+ "ON m.entity = 'attendance' AND m.new_id = a.id "
							+ "WHERE m.legacy_id = 102 AND a.check_out IS NULL "
							+ "AND a.exception_type_id IS NOT NULL "
							+ "AND a.check_in = TIMESTAMPTZ '2026-03-03 00:00:00+00'")).isEqualTo(1);

			// --- transform 1: EAV collapsed into typed columns, list joined in order
			// Scoped to the migrated company: other tests write their own
			// company_settings rows into the shared database.
			try (ResultSet rs = st.executeQuery(
					"SELECT s.weekly_off_days, s.overtime_rate, s.pay_overtime FROM company_settings s "
							+ "JOIN migration.id_map m ON m.entity = 'companies' AND m.new_id = s.company_id "
							+ "WHERE m.legacy_id = 1")) {
				rs.next();
				assertThat(rs.getString(1)).isEqualTo("Friday,Saturday");
				assertThat(rs.getBigDecimal(2)).isEqualByComparingTo("150");
				assertThat(rs.getObject(3, Boolean.class)).isFalse();
			}

			// --- transform 2: the granted flag became ALLOW overrides, the
			// ungranted one produced nothing
			assertThat(scalar(st,
					"SELECT count(*) FROM membership_permission_overrides o "
							+ "JOIN permissions p ON p.id = o.permission_id "
							+ "JOIN migration.id_map m ON m.entity = 'tenant_memberships' AND m.new_id = o.membership_id "
							+ "WHERE p.permission_key LIKE 'branches.%' AND o.effect = 'ALLOW'")).isEqualTo(2);
			assertThat(scalar(st,
					"SELECT count(*) FROM membership_permission_overrides o "
							+ "JOIN permissions p ON p.id = o.permission_id "
							+ "JOIN migration.id_map m ON m.entity = 'tenant_memberships' AND m.new_id = o.membership_id "
							+ "WHERE p.permission_key LIKE 'shifts.%'")).isZero();
			// can_employees (14) resolves through id_map like any other flag,
			// even though 14 shares its membership with 12 -- all 5 keys land
			// on that one shared row.
			assertThat(scalar(st,
					"SELECT count(*) FROM membership_permission_overrides o "
							+ "JOIN migration.id_map m ON m.entity = 'tenant_memberships' AND m.new_id = o.membership_id "
							+ "WHERE m.legacy_id = 14")).isEqualTo(5);

			// --- requests carries approver, decision time and notes, which
			// the load previously dropped: approver_id resolves through the
			// same tenant_memberships map hr_permissions uses.
			try (ResultSet rs = st.executeQuery(
					"SELECT r.notes, r.status, r.decided_at, am.legacy_id AS approver_legacy_id "
							+ "FROM requests r "
							+ "JOIN migration.id_map m ON m.entity = 'requests' AND m.new_id = r.id "
							+ "JOIN migration.id_map am ON am.entity = 'tenant_memberships' "
							+ "     AND am.new_id = r.approver_membership_id "
							+ "WHERE m.legacy_id = 200")) {
				assertThat(rs.next()).isTrue();
				assertThat(rs.getString("notes")).isEqualTo("Doctor appointment");
				assertThat(rs.getString("status")).isEqualTo("APPROVED");
				assertThat(rs.getLong("approver_legacy_id")).isEqualTo(11);
				assertThat(rs.getObject("decided_at", OffsetDateTime.class).toInstant())
						.isEqualTo(Instant.parse("2026-03-04T10:00:00Z"));
			}

			// --- counts artifact: finalize counts the real target table, which
			// is correct for production (empty before cutover) but not for this
			// suite, where every prior test's rows are still sitting in the same
			// shared `attendance` table. Assert it matches a live recount rather
			// than a literal 2, which is what the artifact actually promises.
			long attendanceTotal = scalar(st, "SELECT count(*) FROM attendance");
			assertThat(scalar(st,
					"SELECT rows FROM migration.load_counts WHERE entity = 'attendance'"))
					.isEqualTo(attendanceTotal);

			// --- the sequence was advanced, so a fresh insert cannot collide
			long freshCompany = scalar(st,
					"INSERT INTO companies (name, phone) VALUES ('Post Cutover', '+20999') RETURNING id");
			assertThat(freshCompany).isGreaterThan(
					scalar(st, "SELECT new_id FROM migration.id_map WHERE entity = 'companies' AND legacy_id = 1"));

			// --- rerun safety: running the whole program again changes nothing
			long attendanceBefore = scalar(st,
					"SELECT count(*) FROM attendance a "
							+ "JOIN migration.id_map m ON m.entity = 'attendance' AND m.new_id = a.id");
			long mapBefore = scalar(st, "SELECT count(*) FROM migration.id_map");
			long departmentBranchesBefore = scalar(st,
					"SELECT count(*) FROM department_branches db "
							+ "JOIN migration.id_map dm ON dm.entity = 'departments' AND dm.new_id = db.department_id "
							+ "WHERE dm.legacy_id = 20");
			st.execute(load);
			st.execute(finalize);
			assertThat(scalar(st,
					"SELECT count(*) FROM attendance a "
							+ "JOIN migration.id_map m ON m.entity = 'attendance' AND m.new_id = a.id"))
					.isEqualTo(attendanceBefore);
			assertThat(scalar(st, "SELECT count(*) FROM migration.id_map")).isEqualTo(mapBefore);
			assertThat(scalar(st,
					"SELECT count(*) FROM department_branches db "
							+ "JOIN migration.id_map dm ON dm.entity = 'departments' AND dm.new_id = db.department_id "
							+ "WHERE dm.legacy_id = 20")).isEqualTo(departmentBranchesBefore);
			// Scoped through the real tables (companies -> tenant_memberships),
			// not id_map directly: 12 and 14 share one membership, so joining
			// id_map straight to the overrides would double-count that row's
			// 5 grants once per legacy id mapped onto it.
			assertThat(scalar(st,
					"SELECT count(*) FROM membership_permission_overrides o "
							+ "JOIN tenant_memberships t ON t.id = o.membership_id "
							+ "JOIN migration.id_map m ON m.entity = 'companies' AND m.new_id = t.company_id "
							+ "WHERE m.legacy_id IN (1, 2)")).isEqualTo(7);
		}
	}

	@Test
	void anUnmappedPermissionFlagAbortsTheLoad() throws Exception {
		String ddl = emit("ddl");
		String load = emit("load");

		try (Connection connection = superuser(); Statement st = connection.createStatement()) {
			st.execute("DROP SCHEMA IF EXISTS migration CASCADE");
			st.execute(ddl);
			stageFixture(st, "6661");
			// A flag this dump has and PERMISSION_MAP does not.
			st.execute("ALTER TABLE migration.stg_hr_permissions ADD COLUMN can_teleport TEXT");

			assertThat(org.assertj.core.api.Assertions.catchThrowable(() -> st.execute(load)))
					.hasMessageContaining("unmapped hr_permissions flags")
					.hasMessageContaining("can_teleport");
		}
	}

}
